### DISCUSSION TITLE
Ch18. Grafana

### DISCUSSION THREAD

**Discussion by yjinheon** [studykuberstep24/studykuberstep24#110] [진헌]
## 01. 모니터링 지표들

구글에서 제시한 Golden Signals

- Latency : 요청에 대한 응답시간
- Traffic : 요청량
- Errors : 단순 에러 외 서비스 지연을 포함한 전체 장애 건수
- Saturation : 트래픽 증가 혹은 노드 장에 등의 상황이 발생하였을 때 예비 가용 자원 사용량

### 프로메테우스 + 그라파나용 minikube profile 실행

```bash
#!/bin/bash

######################
# create the cluster #
######################

# 3개 노드, 각 노드에 추가디스크
minikube start \
  --cpus 2 \
  --memory 4096 \
  --disk-size 20g \
  --driver virtualbox \
  --profile prometheus-test

# 필요한 애드온 활성화
minikube addons enable ingress --profile prometheus-test

echo "minikube started with profile prometheus-test"



```

### Helm Chart 설치

- minikube 환경에서 grafana ip에 정상적으로 접근하기 위해 service type을 NodePort로 설정
- grafana의 value.yaml에는 nodePort 서비스일 경우의 port 필드가 없기 때문에 직접 추가 필요
- pvc 구성 이슈로 persistentVolumeClaim을 사용하지 않음

```yaml
service:
  enabled: true
  type: NodePort
  # Set the ip family policy to configure dual-stack see [Configure dual-stack](https://kubernetes.io/docs/concepts/services-networking/dual-stack/#services)
  ipFamilyPolicy: ""
  # Sets the families that should be supported and the order in which they should be applied to ClusterIP as well. Can be IPv4 and/or IPv6.
  ipFamilies: []
  loadBalancerIP: ""
  loadBalancerClass: ""
  loadBalancerSourceRanges: []
  port: 80
  nodePort: 30104 # 직접 추가
  targetPort:
    3000
    # targetPort: 4181 To be used with a proxy extraContainer
  ## Service annotations. Can be templated.
  annotations: {}
  labels: {}
  portName: service
  # Adds the appProtocol field to the service. This allows to work with istio protocol selection. Ex: "http" or "tcp"
  appProtocol: ""
  sessionAffinity: ""
```

### Grafana 로그인 후 default prometheus 설정 확인

![image](https://github.com/user-attachments/assets/9ff54383-960c-4e13-98d6-6e4ff34754cd)

### Compute resource cluster

![image](https://github.com/user-attachments/assets/ca482e8e-2304-4e7c-aac4-05921a48b411)

### Node Exporter

![image](https://github.com/user-attachments/assets/339a5695-aca9-4354-aa89-79d7e38f69d0)

### 커스텀 쿠버네티스 리소스메트릭 추가

![image](https://github.com/user-attachments/assets/4ec32a86-c0e0-4a21-bde9-590d0ec51952)

### Ngins 서비스 모니터링

![image](https://github.com/user-attachments/assets/62a29537-164d-46cd-a445-2d45fd54c2bc)

## 서비스 구성

![image](https://github.com/user-attachments/assets/98f9b898-0e65-4ae0-b2d6-989a83d63a9b)

## Key Takeaways

- kube-state-metrics에서 클러스터 전반의 정보 제공
- 어플리케이션 모니터링을 등록하기 위해서는 어플리케이션을 설치할 때 Exporter Pod 추가 필요
- Immutable Infrastructure의 핵심은 infra를 수정하지 않고 교체한다는 것
