### DISCUSSION TITLE
19. Alertmanager

### DISCUSSION THREAD

**Discussion by yjinheon** [studykuberstep24/studykuberstep24#116] [진헌]
## 01. alertmanager

Concept

---

**_Concept_**

- **Alertmanager** : Prometheus 생태계에서 Alert를 처리하고 알림을 전달하는 컴포넌트
- **Alert 라우팅** : 받은 Alert를 적절한 채널과 담당자에게 전달하는 과정
- **Alert 그룹화** : 비슷한 성격의 Alert들을 묶어서 스팸을 방지하는 기능
- **Alert 억제** : 이미 알려진 문제나 상위 문제로 인한 하위 Alert를 차단하는 기능

---

### WebHook Url 생성

![image](https://github.com/user-attachments/assets/8f966e83-ee86-45ea-8df6-3236f97d4a01)

### Slack WebHook Url Alertmanager Config에 등록

![image](https://github.com/user-attachments/assets/42037f53-93ef-4b99-a2b4-18698cd2d484)

### alertmanager pod 상세정보에서 설정내역 확인

![image](https://github.com/user-attachments/assets/0818b0e7-2203-42f4-9251-0e8eb45f85bb)

### slack channel에서 Alertmanager 메시지 수신 확인

![image](https://github.com/user-attachments/assets/10048b6f-f12f-43ae-a94c-fb0b869984e6)

## 02. AlertManager 기능검증

- 싱글노드로 실습중

### Prometheus Rules 확인

- 프로메테우스는 이벤트를 감시하다 위에 설정한 임계값을 초과하면 경고를 발생시킴

```bash
k get prometheusrules.monitoring.coreos.com
```

![image](https://github.com/user-attachments/assets/00abbac1-f54c-481b-8930-8430cd785a73)

### alertmanager silence 기능 

- 시스템 유지보수 등과 같이 서비스를 계획적으로 중단할 경우 alert전송을 일시중지할 수 있다.

![image](https://github.com/user-attachments/assets/e1f0c781-2ac4-4ddc-b0f8-c8280e953d55)

### 사용자정의 prometheus 정책 설정

- general.rules로 상세경고메시지 확인

```bash
k describe prometheusrules.monitoring.coreos.com prometheus-kube-prometheus-general.rules
```

- 시트템 경고 상세 설정. up 메트릭이 0일 경우 경고 발생
- 모니터링 대상 다운
- 10분간 pending 상태 지속하면 Firing 상태로 변경

![image](https://github.com/user-attachments/assets/dc351554-1487-4256-a843-2a8e25160910)

### 커스텀 경고정책 예제

```yaml

    - alert: HighCPUUsage # 커스텀 규칙 명 정의
      # 노드의 CPU 사용률이 80% 이상일 때
      expr: 100 - (avg by (instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
      for: 10m # 상태가 10분간 지속될 경우 알림
      labels:
        severity: warning
        category: resource
      annotations:
        summary: "높은 CPU 사용률 감지"
        description: "노드 {{ $labels.instance }}에서 CPU 사용률이 {{ printf \"%.2f\" $value }}%입니다."
        impact: "성능 저하 가능성"

    - alert: HighMemoryUsage
      # 메모리 사용률이 85% 이상일 때
      expr: (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100 > 85
      for: 5m
      labels:
        severity: critical
        category: resource
      annotations:
        summary: "높은 메모리 사용률"
        description: "노드 {{ $labels.instance }}에서 메모리 사용률이 {{ printf \"%.2f\" $value }}%입니다."
        action_required: "메모리 정리 또는 스케일링 필요"

    - alert: DiskSpaceLow
      # 디스크 사용률이 90% 이상일 때
      expr: (1 - (node_filesystem_avail_bytes{fstype!="tmpfs"} / node_filesystem_size_bytes{fstype!="tmpfs"})) * 100 > 90
      for: 1m
      labels:
        severity: critical
        category: storage
      annotations:
        summary: "디스크 공간 부족"
        description: "{{ $labels.instance }}의 {{ $labels.mountpoint }}에서 디스크 사용률이 {{ printf \"%.2f\" $value }}%입니다."
        urgency: "즉시 조치 필요"

- alert: HighHTTPErrorRate
      # 5분간 HTTP 5xx 에러율이 5% 이상일 때
      expr: rate(http_requests_total{status=~"5.."}[5m]) / rate(http_requests_total[5m]) * 100 > 5
      for: 3m
      labels:
        severity: warning
        category: application
      annotations:
        summary: "HTTP 에러율 증가"
        description: "서비스 {{ $labels.service }}에서 HTTP 5xx 에러율이 {{ printf \"%.2f\" $value }}%입니다."
        troubleshooting: "로그 확인 및 애플리케이션 상태 점검 필요"
```

### Groups와 category의 차이

- Groups는 Prometheus가 알림 규칙들을 물리적으로 처리하는 단위
- 같은 그룹 내의 규칙들은 병렬로 처리되지만, 그룹 간에는 순차적으로 처리됨
- 이는  한 그룹에 매우 복잡하고 시간이 오래 걸리는 쿼리가 있다면, 다른 그룹의 알림 평가가 지연될 수 있기 때문. 따라서 비슷한 처리 시간과 우선순위를 가진 규칙들을 같은 그룹으로 묶음

## 03. Key Takeaway
---

**_Key Takeaway_**

- 기본적으로 alert생성의 주체는 prometheus 서버이고 alert manager는 라우팅, 그룹화, notification 채널로 메시지 전송을 담당한다.
- 시스템 유지보수 작업일 때 알림발송을 일시 중단시키는 Silence 기능 존재
- prometheus는 임계값, 메시지 발생 간격 설정 등의 시스템 경고 정책을 별도의 CRD로 관리할 수 있음
- crd에서 표현식(expr) 형태로 알림 발송 조건을 작성할 수 있으며 이것이 true가 되면 알림이 발송됨

---
