### DISCUSSION TITLE
ch22. 역할 기반 접근 제어(PBAC) 설정

### DISCUSSION THREAD

**Discussion by YuDeokRin** [studykuberstep24/studykuberstep24#136] [덕린]
# ch22. 역할 기반 접근 제어(PBAC) 설정

## ✅개요

- 인증
    - 로그인 등의 절차를 거쳐서 사용자가  누구인지 확인하는 것
- 인가
    - 인증 과정을 거치고 사용자가 어떤 권한을 가지고 있는지 확인하는 행위

쿠버네티스는 인증, 인가를 PBAC(Role Based Access Control, 역할 기반 접근 제어)로 구현한다.

### ➡️쿠버네티스 멀티테넌시(multitenancy)환경을 지원

가장 많이 구현하는 멀티테넌시 사례로 사용자별로 권한을 구분해서 네임스페이스(가상 클러스터) 단위로

1. 특정 기능(조회 등)만 가능하도록 제한
2. 네트워크 정책을 통한 외부 네임스페이스에서의 접근을 차단
3. 네임스페이스 단위로 리소스 할당량을 지정해 자원을 제한

- 쿠버네티스에서 지원하는 역할 기반 접근 제어의 주요 구성요소

<img width="842" alt="image" src="https://github.com/user-attachments/assets/32f15f4d-a66d-42c1-a54e-439d5a4223df" />

- 실습 과제

```
1. 특정 네임스페이스(wordpress)의 모든 권한을 가지는 개발자 계정을 생성하고, 해당 계정으로 클러스터에 접속합니다.
새로운 Role(wordpress-namespace-full-access)과 RoleBinding을 생성하여, wordpress 네임스페이스의 모든 권한을 할당합니다.
새로운 ServiceAccount(wordpress-sa)를 생성하고, 앞에서 언급한 RoleBinding 권한을 지정합니다.
해당 ServiceAccount의 토큰 정보를 확인합니다.
kubeconfig 파일(~/.kube/config)에 새로운 사용자(wordpress-user)를 생성하여, 해당 토큰 정보를 등록합니다.

2. kubeconfig(ubun01-wordpress) 파일에 새로운 Kubernetes 컨텍스트를 생성합니다.
해당 권한으로 wordpress 네임스페이스에서 파드를 생성하고, 생성한 파드가 정상적으로 조회되는지 확인합니다.
그 후, 다른 네임스페이스에서는 정상적으로 파드를 생성할 수 있는지 비교합니다.
```

## 1️⃣ Role/RoleBinding과 ClusterRole/ClusterRoleBinding 이해

- 쿠버네티스 환경의 사용자 권한 관련 설정
    - 예) 파드와 네임스페이스의 조회, 생성 등은 역할(Role 또는 ClusterRole)로 지정

- Role은 특정 네임스페이스에 속하는 파드, 서비스 등의 리소스를 지정하는 경우에 사용하고 두번째 ClusterRole은 네임스페이스에 속하지 않는 노드, PV 혹은 단일 네임스페이스가 아닌 전체 네임스페이스의 파드를 조회(k get pod -all-namespaces)하는 권한 등에 사용
    - 예) wordpress라는 네임스페이스에서만 권한을 가지고 다른 네임스페이스에 대해서는 전혀 권한이 없는 Role과 RoleBinding을 만들 수 있다.
- 특정 네임스페이스의 권한을 가지는  Role 및 RoleBinding

<img width="418" alt="image 1" src="https://github.com/user-attachments/assets/6ae88792-300a-4067-91e5-41b49bd6cb23" />

- wordpress 네임스페이스의 전체 권한을 가지는 Role(full-namespace-role.yml)

```yaml
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: wordpress-namespace-full-access
  namespace: wordpress
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["batch"]
  resources:
    - jobs
    - cronjobs
  verbs: ["*"]
```

- namespace: wordpress
    - Role은 네임스페이스 단위로 할당하므로, 반드시 네임스페이스를 지정
- apiGroups: ["", "extensions", "apps"], resources: ["*"]
    - 리소스가 속한 **API Group 이름을 명시**
    - 특수 문자 를 사용하면 **전체 리소스**를 선택
    - API Group과 해당 그룹에 속한 리소스는 `k api-resources` 명령어로 확인
- verbs: ["*"]
    - 리소스의 **생성(create), 조회(get)** 등 특정 권한을 **동사 형태로 지정**
    - 해당 동사는 **HTTP API 동사**와 연관
    - `resources`와 마찬가지로 특수 문자 를 지원하여 **모든 동작을 허용 가능**

- 이제 해당 Role을 사용하는 RoleBinding을 생성

- wordpress 네임스페이스에 대한 RoleBInding(namespace-rolebinding.yaml)

```yaml
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: wordpress-namespace-full-access-rb
  namespace: wordpress
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: wordpress-namespace-full-access
subjects:
- kind: ServiceAccount
  name: wordpress-sa
  namespace: wordpress
```

- roleRef: name: wordpress-namespace-full-access
    - RoleBinding이 지정하는**Role**은항목의 name으로 지정한다. 방금 생성한 wordpress-namespace-full-access을 지정해서 **Role과 RoleBinding을 연결한다.**
- subjects:  -kind: ServiceAccount
    - RoleBinding의 주체로는**ServiceAccount, User, Group** 등이 있다. 이번 예제에서는 **토큰을 사용해 사용자와 연결**하기 위해 **ServiceAccount**를 사용한다.
- name: wordpress-sa
    - 서비스 어카운트는 이름을 임의로 wordpress-sa로 지정한다. 서비스 어카운트는 아직 생성하지 않았지만, 이처럼 먼저 RoleBinding에 지정할 수 있다. **RoleBinding을 생성한 후에**해당**ServiceAccount 오브젝트를 생성**해도 괜찮다.
    

## 2️⃣ ServiceAccount와 User, kubeconfig 파일 이해 : 특정 네임스페이스 권한만 가지는 사용자 생성

- 서비스 어카운트는 사용자가 쿠버네티스 API 서버를 이용하기 위한 인증 과정을 처리하는 역할을 한다.

<img width="294" alt="image 2" src="https://github.com/user-attachments/assets/05e0900e-5b36-459c-bc48-bd84286df949" />

- RoleBinding과 서비스 어카운트 연결

- wordpress 네임스페이스의 서비스 어카운트(namespace-sa.yml)

```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: wordpress-sa
  namespace: wordpress
```

- name : wordpress-sa
    - RoleBinding을 생성할 때 지정한 이름에 맞게 서비스 어카운트를 생성하면 자동으로 RoleBinding과 연결된다.

- 서비스 어카운트 리스트(wordpress-sa)를 확인할 수 있다.

```yaml
[spkr@erdia22 ch22 (ubun01:wordpress)]$ kubectl describe rolebindings.rbac.authorization.k8s.io wordpress-namespace-full-access-rb -n wordpress

Name:         wordpress-namespace-full-access-rb
Labels:       <none>
Annotations:  <none>

Role:
  Kind:  Role
  Name:  wordpress-namespace-full-access

Subjects:
  Kind            Name           Namespace
  ----            ----           ---------
  ServiceAccount  wordpress-sa   wordpress

```

- 서비스 어카운트와 사용자의 관계

<img width="469" alt="image 3" src="https://github.com/user-attachments/assets/3c17a3e4-deff-451f-ac6a-960bf473ab45" />

## 3️⃣ 멀티테넌시 환경의 쿠버네티스 구성: 사용자별 네임스페이스 단위의 권한 제한

- 쿠버네티스 환경의 멀티테넌시(다중 사용자 환경) 구현은 일반적으로 네임스페이스 단위로 구분한다.

- 이번장에서는 멀티테넌시 실습 진행

- 네임스페이스 단위 사용자 권한 제어

<img width="706" alt="image 4" src="https://github.com/user-attachments/assets/0d7165a9-2714-4f3e-b83e-983b73a51c24" />

1. 우선 사용자를 변경 → 앞에서 설치한 `kctx`(context)를 사용하면 **편리하게 컨텍스트를 변경**할 수 있고,**컨텍스트에 포함되는 사용자도 함께 변경된다.**

만약 `kctx`를 설치하지 않았다면, `kubectl config current-context`,`kubectl config set-context`, `kubectl config use-context wordpress-ubuntu`와 같은`kubectl config` 관련 명령어들을 직접 사용해야 하므로 불편하다.(비효율)

- 현재 사용 가능한 컨텍스트의 목록을 출력한다.

```bash
[spkr@erdia22 ch22 (ubun01:wordpress)]$ k ctx
ubun01
wordpress-ubun01
```

- 새롭게 생성한 wordpress-ubun01 컨텍스트를 확인할 수 있다. 컨텍스트 변경

```bash
[spkr@erdia22 ch22 (ubun01:wordpress)]$ k ctx wordpress-ubun01
Switched to context "wordpress-ubun01".
```

- 컨텍스트 변경 → 컨텍스트 사용자 권한 변경

```bash
[spkr@erdia22 ch22 (wordpress-ubun01:wordpress)]$ k get pod
No resources found in wordpress namespace.

[spkr@erdia22 ch22 (wordpress-ubun01:wordpress)]$ k create deployment nginx --image=nginx
deployment.apps/nginx created

[spkr@erdia22 ch22 (wordpress-ubun01:wordpress)]$ k get pod
NAME                      READY   STATUS    RESTARTS   AGE
nginx-8f458dc5b-7r6wr     1/1     Running   0          18s

```

```bash
##get 명령어 실행 시 에러가 발생
[spkr@erdia22 ch22 (wordpress-ubun01:wordpress)]$ k get pod -n default
Error from server (Forbidden): pods is forbidden: 
User "system:serviceaccount:wordpress:wordpress-sa" cannot list resource "pods" in API group "" in the namespace "default"

##리소스 생성도 불가
[spkr@erdia22 ch22 (wordpress-ubun01:wordpress)]$ k create deployment nginx --image=nginx -n default
error: failed to create deployment: 
deployments.apps is forbidden: 
User "system:serviceaccount:wordpress:wordpress-sa" cannot create resource "deployments" in API group "apps" in the namespace "default"

```

```bash
## 네임스페이스 조회 시 에러가 발생
[spkr@erdia22 ch22 (wordpress-ubun01:wordpress)]$ k get ns
Error from server (Forbidden): namespaces is forbidden: 
User "system:serviceaccount:wordpress:wordpress-sa" cannot list resource "namespaces" in API group "" at the cluster scope

## PV 조회 에러
[spkr@erdia22 ch22 (wordpress-ubun01:wordpress)]$ k get pv
Error from server (Forbidden): persistentvolumes is forbidden: 
User "system:serviceaccount:wordpress:wordpress-sa" cannot list resource "persistentvolumes" in API group "" at the cluster scope

## 실습을 종료하면 kubeconfig 컨텍스트를 기존 어드민 컨텍스트인 'ubun01'로 변경된다.
[spkr@erdia22 ch23 (wordpress-ubun01:wordpress)]$ k ctx ubun01
Switched to context "ubun01".

```
