### DISCUSSION TITLE
ch23. 애플리케이션 부하 테스트와 고가용성 테스트

### DISCUSSION THREAD

**Discussion by yeongki0944** [studykuberstep24/studykuberstep24#138] [영기]
# 01. 데모 용도의 방명록 서비스 설치

## guestbook namespace 생성
```bash
kubectl create namespace guestbook

kubectl config view

kubectl config set-context --current --namespace=guestbook
```

## guestbook-front 리소스 배포
```bash
kubectl apply -f guestbook-front.yaml
```

```yaml
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: guestbook
    tier: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: guestbook
    tier: frontend
---
apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: guestbook
      tier: frontend
  replicas: 3
  template:
    metadata:
      labels:
        app: guestbook
        tier: frontend
    spec:
      containers:
      - name: php-redis
        image: gcr.io/google-samples/gb-frontend:v4
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: GET_HOSTS_FROM
          value: dns
        ports:
        - containerPort: 80
```
![image](https://github.com/user-attachments/assets/81dd1727-3156-482c-8a3b-5da54fa8f0ff)

## guestbook-redis 리소스 배포

```bash
kubectl apply -f guestbook-redis.yaml
```

```yaml
apiVersion: v1
kind: Service
metadata:
  name: redis-master
  labels:
    app: redis
    role: master
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: redis
    role: master
---
apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: redis-master
spec:
  selector:
    matchLabels:
      app: redis
      role: master
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
        role: master
    spec:
      containers:
      - name: master
        image: k8s.gcr.io/redis:e2e  # or just image: redis
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-slave
  labels:
    app: redis
    role: slave
spec:
  ports:
  - port: 6379
  selector:
    app: redis
    role: slave
---
apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: redis-slave
spec:
  selector:
    matchLabels:
      app: redis
      role: slave
  replicas: 2
  template:
    metadata:
      labels:
        app: redis
        role: slave
    spec:
      containers:
      - name: slave
        image: gcr.io/google_samples/gb-redisslave:v1
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: GET_HOSTS_FROM
          value: dns
        ports:
        - containerPort: 6379
```
![image](https://github.com/user-attachments/assets/fb2425f9-a21c-4db4-815d-4cbb79dcad5c)

## Pod 배포 확인
![image](https://github.com/user-attachments/assets/c2925059-9f7a-42d0-adf9-3a746c241666)

#### 이슈 발견
```bash
kubectl get pods
# 결과: STATUS가 ImagePullBackOff로 표시됨
```

#### 상세 에러 확인
```bash
kubectl describe pod [pod-name] | grep -A 50 -E 'Event'
```

```
root@k8s-master:~/kubepractice/ch23# kubectl describe pod frontend-69b9556bc-npnmb | grep -A 50 -E 'Event'
Events:
  Type     Reason     Age                     From               Message
  ----     ------     ----                    ----               -------
  Normal   Scheduled  7m45s                   default-scheduler  Successfully assigned guestbook/frontend-69b9556bc-npnmb to k8s-worker1
  Warning  Failed     6m20s (x6 over 7m44s)   kubelet            Error: ImagePullBackOff
  Normal   Pulling    6m5s (x4 over 7m44s)    kubelet            Pulling image "gcr.io/google-samples/gb-frontend:v4"
  Warning  Failed     6m5s (x4 over 7m44s)    kubelet            Failed to pull image "gcr.io/google-samples/gb-frontend:v4": rpc error: code = NotFound desc = failed to pull and unpack image "gcr.io/google-samples/gb-frontend:v4": failed to resolve reference "gcr.io/google-samples/gb-frontend:v4": gcr.io/google-samples/gb-frontend:v4: not found
  Warning  Failed     6m5s (x4 over 7m44s)    kubelet            Error: ErrImagePull
  Normal   BackOff    2m42s (x21 over 7m44s)  kubelet            Back-off pulling image "gcr.io/google-samples/gb-frontend:v4"
```

#### 이슈 해결
도커 이미지가 없어서 발생했던 오류 > 도커허브에 존재하는 다른 이미지로 변경
https://hub.docker.com/r/forestgun007/google-samples-gb-frontend
![image](https://github.com/user-attachments/assets/b798b3d1-5783-49f7-ac82-9d26cc46c4e2)

## guestbook svc 확인

![image](https://github.com/user-attachments/assets/a21f3885-0e11-483f-84fd-b9ced1ca4bf1)

<img width="973" alt="image" src="https://github.com/user-attachments/assets/3e295d23-5bfa-4213-b8d7-8761148f78db" />

# 02. k6를 이용한 웹 부하 테스트

## 부하테스트 도구
- JMeter
- k6

## 부하테스트 용어
- SLO(Service Level Object / 서비스 수준 목표) : 서비스 수준을 정량적으로 정의한 것 
  - 사용자 관점에서 최대한 단순하게 정의
    - 예: 동시 사용자 10,000명 접속 시 첫 페이지 응답 속도의 99%가 1초 이내여야 한다.
- SLI(Service Level Indicator / 서비스 수준 척도) : 서비스 수준 목표를 측정하기 위한 정량적인 판단 기준
  - ❌ 잘못된 SLI : CPU, 메모리, 디스크 I/O 등 자원 사용량 (시스템 운영자 관점)
  - ✅ 정상적인 SLI : 서비스 응답 속도, 수용 가능한 동시/활성 사용자 (사용자 관점)
- SLA(Service Level Agreement / 서비스 수준 협약) : SLO, SLI를 바탕으로 외부 고객에게 공개하는 것 

## k6 설치

```bash
# GPG 키 추가
sudo gpg -k
sudo gpg --no-default-keyring --keyring /usr/share/keyrings/k6-archive-keyring.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C5AD17C747E3415A3642D57D77C6C491D6AC1D69

# 저장소 추가
echo "deb [signed-by=/usr/share/keyrings/k6-archive-keyring.gpg] https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list

# 패키지 목록 업데이트
sudo apt-get update

# k6 설치
sudo apt-get install k6
```

![image](https://github.com/user-attachments/assets/31ce28e2-c96a-4e88-8577-57acbea4846b)

## k6 cli
![image](https://github.com/user-attachments/assets/20407017-da0e-4b7b-b85b-0da4056c99a4)

![image](https://github.com/user-attachments/assets/09cd4c3f-3c3d-4148-b0d8-50eb54aed3ef)

## k6 부하테스트 
![image](https://github.com/user-attachments/assets/564e8c55-92c8-44db-a2ce-bc437add1fdd)

![image](https://github.com/user-attachments/assets/6783f4c0-8812-4ef3-9792-6828fce782c5)

### k6 결과
![image](https://github.com/user-attachments/assets/4517142b-bbb4-4318-bfd1-2fc64b74c15e)

- 500 max VUs
  - k6에서 부하테스트를 실행하는 사용자 수 Virtual Users
  - stages.js의 target으로 지정한 500사용자와 동일
- checks
  - HTTP 응답코드 200 결과
- p(90) : 응답속도 분포(percentiles)로서 가장 빠른 속도에서 시작해서 90번째 응답속도
- p(95) : 응답속도 분포(percentiles)로서 가장 빠른 속도에서 시작해서 95번째 응답속도

# 03. 애플리케이션 고가용성 테스트

### 노드 현황 체크
```bash
kubectl get node -o wide -A
```
![image](https://github.com/user-attachments/assets/52b9b12d-c2fb-4d08-a005-12485d88c9f9)

### 전체 파드 조회
```bash
kubectl get pod -o wide -A
```
![image](https://github.com/user-attachments/assets/3c486de5-2b2f-4c54-b620-da23a17c319c)

### 노드별 파드 실행 개수 조회
![image](https://github.com/user-attachments/assets/a4dd355d-5f96-475a-ad41-2001c54c1115)

### k8s-worker1 - drain 시도
```bash
kubectl drain k8s-worker1
```
![image](https://github.com/user-attachments/assets/a1ca1b96-9fb9-471b-80b4-f2c7dccf687c)

### k8s-worker1 - drain 옵션 추가(--delete-emptydir-data --ignore-daemonsets)

```bash
kubectl drain k8s-worker1 --delete-emptydir-data --ignore-daemonsets
```
kubectl drain k8s-worker1 --delete-emptydir-data --ignore-daemonsets

```bash
kubectl drain k8s-worker1 --delete-emptydir-data --ignore-daemonsets --force
```
![image](https://github.com/user-attachments/assets/c9fe1433-bb81-49ce-85a7-7e8d99dce6f7)

### drain이후 pending 중인 pod들
- openebs-hostpath : 노드를 종료하면 다른 노드에는 기존 파드가 사용하는 데이터가 없어 실행되지 못함
![image](https://github.com/user-attachments/assets/da5b8087-7155-4e6f-91a1-367d6c0ab24e)

- 파드가 생성조차 안된것 같음
![image](https://github.com/user-attachments/assets/4436c055-c341-405b-a694-3a205bb01269)

![image](https://github.com/user-attachments/assets/e0c5b3c3-6a82-4c9e-9ab4-447bd27eb965)

![image](https://github.com/user-attachments/assets/05ee131e-6ab7-4d99-a622-af5439aaac2f)

### node drain시 cordon(파드 실행이 금지)된 모습
![image](https://github.com/user-attachments/assets/fe419a67-d5ee-41e6-bc4b-278e6f074c53)

### node - cordon 해지
```bash
kubectl uncordon k8s-worker1

kubectl uncordon k8s-worker2
```

![image](https://github.com/user-attachments/assets/2e2f7a14-0a34-4a4f-bbf5-94f1f3a81a2b)
