### DISCUSSION TITLE
ch23.24

### DISCUSSION THREAD

**Discussion by YuDeokRin** [studykuberstep24/studykuberstep24#143] [덕린]
# ch23. 애플리케이션 부하 테스트와 고가용성 테스트

## ✅이번 챕터의 실습 과제

1. 데모 용도의 방명록 서비스를 설치한다.
2. 부하테스트 도구인 K6를 이용해 방명록 서비스의 부하 테스트를 수행한다. (초당 500명 사용자 접속)
3. 노드 내에서 실행 중인 모든 파드를 다른 노드로 이전(drain)합니다. 방명록 서비스를 구성하는 전체 파드를 순차적으로 다운시키면서 서비스 이상 여부를 확인한다. 서비스 이상 여부는 while, curl 스크립트를 이용해 1초마다 접속해서 검증한다. 
4. 특정 노드를 다운시켜 서비스 이상 여부를 확인한다.

## 1️⃣ 데모 용도의 방명록 서비스 설치

- 부하 테스트 및 고가용성 테스트를 위한 데모 용도의 방명록 서비스를 설치
- 방명록 서비스는 프론트엔드, 레디스에 각각 3개의 파드로 구성
- 

![image](https://github.com/user-attachments/assets/68707cfd-5ea0-4918-9979-4c41ca706144)

```yaml
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: guestbook
spec:
  # 서비스 타입은 LoadBalancer 혹은 NodePort를 사용합니다.
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    app: guestbook
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: guestbook
  # 서비스 고가용성 구성을 위해 3개의 프론트엔드 서비스용 파드를 설치합니다.
  replicas: 3
  template:
    metadata:
      labels:
        app: guestbook
    spec:
      containers:
        - name: php-redis
          # 데모 용도의 방명록(guestbook) 서비스는 구글에서 제공합니다.
          image: gcr.io/google-samples/gb-frontend:v4
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          env:
              - name: GET_HOSTS_FROM
              value: dns
          ports:
              - containerPort: 80
```

- 방명록 서비스에 사용할 guestbook 네임스페이스를 생성하고 프론트엔드 서비스용 파드를 설치합니다.

```bash
[spkr@erdia22 ch22 (ubun01:wordpress)]$ cd ../ch23

[spkr@erdia22 ch23 (ubun01:wordpress)]$ k create ns guestbook
namespace/guestbook created

[spkr@erdia22 ch23 (ubun01:wordpress)]$ k ns guestbook
Context "ubun01" modified.
Active namespace is "guestbook".

[spkr@erdia22 ch23 (ubun01:guestbook)]$ k apply -f guestbook-front.yml
service/frontend created
deployment.apps/frontend created

```

- 백엔드 용도의 레디스를 설치.
    - 레디스는 프라이머리(primary) 파드1개와 세컨더리(secondary) 파드 2개로 총 3개의 파드로 구성한다.
    
    ```yaml
    
    apiVersion: v1
    kind: Service
    metadata:
      name: redis-master
      labels:
        app: redis
        role: master
    spec:
      ports:
        - port: 6379
          targetPort: 6379
      selector:
        app: redis
        role: master
    ---
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      # Redis master 파드를 설치합니다.
      name: redis-master
    spec:
      selector:
        matchLabels:
          app: redis
          role: master
      replicas: 1
      template:
        metadata:
          labels:
            app: redis
            role: master
        spec:
          containers:
            - name: master
              image: k8s.gcr.io/redis:e2e  # or just image: redis
              resources:
                requests:
                  cpu: 100m
                  memory: 100Mi
              ports:
                - containerPort: 6379
    ---
    apiVersion: v1
    kind: Service
    metadata:
      name: redis-slave
      labels:
        app: redis
        role: slave
    spec:
      ports:
        - port: 6379
      selector:
        app: redis
        role: slave
    ---
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      # Redis Slave 파드를 설치합니다.
      name: redis-slave
    spec:
      selector:
        matchLabels:
          app: redis
          role: slave
      replicas: 2
      template:
        metadata:
          labels:
            app: redis
            role: slave
        spec:
          containers:
            - name: slave
              image: gcr.io/google_samples/gb-redisslave:v1
              resources:
                requests:
                  cpu: 100m
                  memory: 100Mi
              env:
                - name: GET_HOSTS_FROM
                  value: dns
              ports:
                - containerPort: 6379
    
    ```
    

- 다음으로 같은 명령어로 레디스 마스터, 슬레이브 파드를 설치

```bash
[spkr@erdia22 ch23 (ubun01:guestbook)]$ k apply -f guestbook-redis.yml
service/redis-master created
deployment.apps/redis-master created
service/redis-slave created
deployment.apps/redis-slave created
```

- 정상적으로 설치되었나 확인

```bash
[spkr@erdia22 ch23 (ubun01:guestbook)]$ k get pod
NAME                                    READY   STATUS    RESTARTS   AGE
frontend-f7d9c57d4-97jzb                1/1     Running   0          12m
frontend-f7d9c57d4-g6ccw                1/1     Running   0          12m
frontend-f7d9c57d4-xcwfw                1/1     Running   0          12m
redis-master-7f9d665c5d-41wn9           1/1     Running   0          4m48s
redis-slave-68d96fd5c4-9g5k2            1/1     Running   0          4m48s
redis-slave-68d96fd5c4-sx7l8            1/1     Running   0          4m48s

```

## 2️⃣ K6를 이용한 웹 부하 테스트

- 이번 절에서는 설치한 방명록 서비스에 테스트 도구(k6)를 이용해 웹 부하 테스트를 실행한다.
- 부하테스트 툴 : JMeter, K6..등등

- 그럼 부하테스트가 필요한 이유는 뭘까?
    - 부하테스트는 우리 서비스가 몇 명의 사용자에게 어느 정도의 응답 속도를 제공할 수 있는지 알아보기 위해 수행
    - 제공 가능한 서비스 수준을 정량적으로 정의한 것을 서비스 수준 목표(Service Level Object; SLO)라고 한다.

- 유의 사항
    - SLI(Service Level Agreement)는 시스템 운영자 관점의 CPU, 메모리, 디스크 I/O 등 자원 사용량이 아닌 서비스를 사용하는 사용자 관점의 서비스 응답 속도, 수용 가능한 동시/활성 사용자 등이어야 한다.
    - SLO 사용자 관점에서 정의해야 하고 최대한 단순하게 정의할 필요가 있다. 앞에서 설치한 테스트 용도의 방명록 서비스를 예를 들면 사용자 응답 속도 측면의 SLO는 다음과 같이 정의할 수 있다.
        - SLO : 동시 사용자 10,000명 접속 시 첫 페이지 응답 속도의 99%가 1초 이내여야한다.
    

```bash
cloud          Run ateston the cloud
convert        Convert a HAR file to a k6 script
help           Help about any command
inspect        Inspect a script or archive
login          Authenticate with a service # 클라우드 로그인
pause          Pause a running test
resume         Resume a paused test
run            Start a load test
scale          Scale a running test
stats          Show test metrics
status         Show test status
version        Show application version
```

- cloud
    - 로컬 환경뿐만 아니라 클라우드 환경에서도 실행할 수 있다. 별도의 비용을 지불하고 클라우드를 사용하면 다양한 클라이언트를 사용할 수 있어 웹 사이트 부하를 증가할 수 있다. 추가로 상세한 성능 리포트, 테스트 이력 등을 확인할 수 있다.
- login
    - 클라우드 환경의 테스트를 진행하려면 k6 클라우드 시스템에 로그인할 필요가 있다.
- run
    - 로컬 환경에서 부하 테스트를 실행할 때 사용한다. k6 run은 명령어 인자로 스크립트를 지정해서 부하 테스트를 실시한다.
    

- IP는 방명록 서비스의 로그밸럭서 타입의 External-IP이다.

```bash
[spkr@erdia22 ch23 (ubun01:guestbook)]$ k get svc -n guestbook
NAME       TYPE           CLUSTER-IP      EXTERNAL-IP     PORT(S)          AGE
frontend   LoadBalancer   10.233.18.55    172.17.29.80    80:30210/TCP     17m
(생략)

```

- 172.17.29.80 로 부하테스트를 진행한다.

- k6를 이용해 부하 테스트를 수행하려면 스크립트가 필요하다. k6는 자바스크립트 기반이다.

```bash
// k6, http 모듈을 불러옵니다.
import http from 'k6/http';
import { check, sleep } from 'k6';

// 3단계로 나눠서 부하 테스트를 실행합니다.
export const options = {
  stages: [
    { duration: '1m', target: 500 },
    { duration: '2m', target: 500 },
    { duration: '30s', target: 0 },
  ],
};

export default function () {
  const res = http.get('http://172.17.29.80/');
  check(res, { 'status was 200': (r) => r.status == 200 });
  sleep(1);
}
```

- **stages**:
    - 정확한 부하 테스트를 위해 **준비**, **실행**, **중지**의 3단계로 나눕니다.
- `duration: '1m', target: 500`
- `duration: '2m', target: 500`
- `duration: '30s', target: 0`
- `duration`은 실행 시간이며, `target`은 부하 테스트를 실행하는 **가상 유저 수이다.**
    - 예를 들어 `"duration: '1m', target: 500"`은 **1분간 500명의 유저로 부하를 발생시켜 테스트를 실행한다**는 의미한다.
    - 가상 유저 생성에 시간이 소요되므로 초기 준비 단계로 1분 동안 500명의 가상 유저를 생성하는 시간을 뒀다.
    - 이후로는 2분 동안 500명의 유저로 실제 테스트를 수행한다.. 마지막으로 30초 동안 유저 수를 0명까지 감소시킨다.
    - 참고로 **k6에서 부하 테스트를 실행하는 사용자를 VU(Virtual User)** 라 하며, 스크립트에서는 이를 `target`이라 한다.
- const res = http.get('[http://172.17.29.80/](http://172.17.29.80/)')
    - 부하 테스트 측정 대상이 되는 IP(혹은 URL)를 지정한다. IP는 앞에서 확인한 방명록 서비스의 LoadBalancer IP로서 각각의 환경에 맞게 수정한다.
    - http.get 메서드를 사용하고 필요에 따라 GET 외에도 아이디/패스워드 입력을 위한 POST, PUT 등 다양한 HTTP 메서드를 사용할 수 있다.
- check
    - 테스트 성공/실패 여부를 기록합니다. 실패가 발생해도 테스트를 중지하지 않고 실패 횟수를 기록합니다.본 테스트에서는 HTTP 응답 코드 200(정상 접속) 리턴 여부를 확인
- sleep(1);
    - 초 간격으로 500명의 가상 유저가 부하 테스트를 실행

## 3️⃣ 애플리케이션 고가용성 테스트

- 이번 절에서는 장애 등의 상황으로 노드와 파드가 종료됐을 때 애플리케이션 서비스에 이상이 없는지 확인하는 고가용성 테스트를 알아보자.

### ✅ 특정 노드 내에서 실행 중인 모든 파드 종료하기

- 명령어 kubectl drain은 노드에서 실행 중인 전체 파드를 종료하고 다른 노드로 이전할 떄 사용하는 명령어이다.

![image 1](https://github.com/user-attachments/assets/369803c5-ab62-4c77-bca3-fcd60e6bf683)

1. 고가용성 테스트에 들어가기 전에 실행 중인 전체 파드 목록을 확인 

```bash
[spkr@erdia22 ~ (ubun01:guestbook)]$ k get pod -o wide -A
NAMESPACE   NAME                                 READY   STATUS    RESTARTS   AGE     IP              NODE         NOMINATED NODE   READINESS GATES
argocd      argocd-application-controller-0      1/1     Running   0          3d22h   10.233.99.80    ubun20-01    <none>           <none>
(생략)

```

1. 모든 네임스페이스에서 실행 중인 파드를 확인하는 옵션은 -A(또는 -all-namespace)이다. 간단히 각 노드마다 실행 중인 파드의 개수를 확인한다.

```bash
# grep {노드이름}, wc -l 옵션을 이용해 실행 중인 파드의 수량을 확인합니다.
[spkr@erdia22 ~ (ubun01:guestbook)]$ k get pod -o wide -A | grep ubun20-01 | wc -l 55
[spkr@erdia22 ~ (ubun01:guestbook)]$ k get pod -o wide -A | grep ubun20-02 | wc -l 48
[spkr@erdia22 ~ (ubun01:guestbook)]$ k get pod -o wide -A | grep ubun20-03 | wc -l 26

```

1. 1번 노드와 2번 노드에서 실행 중인 파드의 수가 비슷하다. 1번 노드의 파드를 종료(drain)한다. 

```bash
[spkr@erdia22 ch23 (ubun01:guestbook)]$ k drain ubun20-01
node/ubun20-01 cordoned

error: unable to drain node "ubun20-01" due to error: [cannot delete Pods with local storage (use --delete-emptydir-data to override): argocd/argocd-application-controller-0,(생략)

```

- 추가 옵션을 지정하지 않고 drain 명령어를 쓰면 위와 같이 에러가 발생한다.
- 해당 경고 메세지를 통해 다른 노드에서 실행되지 않고 종료되는 파드 목록을 확인했으니, 해당 옵션을 추가해서 Drain명령어를 사용하자.

```bash
## --delete-emptydir-data, --ignore-daemonsets 옵션을 추가하면 정상적으로 drain 명령어를 수행할 수 있습니다.
[spkr@erdia22 ch23 (ubun01:guestbook)]$ k drain ubun20-01 --delete-emptydir-data --ignore-daemonsets
node/ubun20-01 already cordoned

(생략)
```
