### DISCUSSION TITLE
ch24. 쿠버네티스 노드 변경과 추가

### DISCUSSION THREAD

**Discussion by vimkim** [studykuberstep24/studykuberstep24#145] [대현]
# 쿠버네티스 노드 변경과 추가

온프레미스 환경은 일반적으로 여유 노드가 충분하지 않아 클러스터 오토스케일러 환경을 구축하기가 어렵습니다 

1. 대체 노드 준비
2. 기존 kubespray 도구의 인벤토리 노드 준비
3. 기존 노드 삭제
4. 새로운 노드 추가 작업

---

1번 노드에 /etc/hosts 파일에 새로 생성한 가상 머신의 IP주소와 호스트명을 등록하고 패스워드 없이 접속할 수 있게 ssh-copy-id 명령어를 실행합니다.

hosts-new01.yml

```
all:
	hosts:
		ubun20-01:
			ansible_host: ubun20-01
		ubun20-02:
			ansible_host: ubun20-02...

	children:
		kube_control_plane:
			hosts:
				ubun20...
				ubun20...
				ubun20...
		kube_node:
			hosts:
		etcd:
			hosts:
		k8s_cluster:
			children:
				kube_control_plane:
					kube_node:
					calico_rr:
				calico_rr:
			calico_rr:
				hosts: {}
```

실행 중인 파드를 다른 노드로 이동

```
k drain ubun20-03 --delete-empty-data --ignore-daemonsets
```

파드 이동이 완료되면 앞에서 수정한 인벤토리 파일을 기준으로 처음 클러스터를 설치할 때 사용한 kubespray 스크립트를 아래 옵션으로 다시 실행

```
ansible-playbook -i inventory/mycluster/hosts-new01.yml cluster.yml --become --become-user=root --limit=etcd,kube_control_plane -e ignore_assert_errors=yes
```

15분 소요

이번에는 etcd 노드가 변경되어 클러스터를 재구성하는 작업이 필요

```
ansible-playbook -i inventory/mycluster/hosts-new01.yml upgrade-cluster.yml -b -v --limit=etcd,kube_control_plane -e ignore_assert_errors=yes
```

18분 소요

```
k delete node ubun20-03
```

---

## 새로운 노드 추가 실습

```
ssh spkr@ubun20-01

sudo vi /etc/hosts
ubun20-01

```

```
ssh-copy-id ubun20-05
ssh ubun20-05

@ubun20-05: sudo vi /etc/sudoers
spkr ALL=(ALL) NOPASSWD:ALL
```

```yaml
all:
	hosts:
		ubun20-01:
			ansible_host
		ubun20-02:
			ansible ...
		...
		ubun20-05:
			ansible_host
...
children:
	kube_control_plane:
		hosts:
			ubun...
	kube_node:
		hosts:
			ubun20-01:
			...
			ubun20-05:
	etcd:
	...
	k8s_cluster:
		...
```

scale.yml 파일을 사용합니다.

```
ansible-playbook -i inventory/mycluster/hosts-new02.yml -b facts.yml
ansible-playbook -i inventory/mycluster/hosts-new02.yml -b --limit=ubun20-05 scale.yml
```

```
$ k create deployment nginx --image nginx --replicas 5
```

### Summary

- 클러스터 설치에 사용한 kubespray 도구를 사용하면 기존 컨트롤 플레인 노드를 포함해서 새로운 노드로 변경할 수 있습니다.
- 앤서블 인벤토리 파일을 수정하고 컨트롤 플레인 노드를 변경하는 경우 스크립트 실행 옵션으로 cluster.yml, upgrade-cluster.yml을 지정합니다.
- 노드 증가시 kubespray 옵션으로 scale.yml을 사용합니다.
