### DISCUSSION TITLE
04. YAML을 활용한 쿠버네티스 오브젝트 관리

### DISCUSSION THREAD

**Discussion by yjinheon** [studykuberstep24/studykuberstep24#24] [진헌]
## 2. YAML을 활용한 쿠버네티스 오브젝트 관리

**플러그인 설치용**

```bash

kubectl krew install ctx ns neat
```

---

**_Concept_**

- **affinity** : k8s에서 특정 조건에 부합하는 노드에 파드를 배치하도록하는 규칙. 기본적으로 이런 특성을 가진 노드에 배치해라 라고 스케줄러에게 요청하는 것과 같다.
- **anti-affinity** : 특정 조건에 부합하는 노드에 파드를 배치하지 않도록 하는 규칙. 이런 특성을 가진 노드에는 배치하지 말아라 라고 스케줄러에게 요청하는 것과 같다.
- **node affinity** : 파드가 특정 노드 집합에 스케줄링되도록 제한. 노드의 레이블을 기반으로 한다. ex) GPU가 있는 노드, SSD 스토리지가 있는 노드와 같은 특정 하드웨어 조건을 가진 노드에 파드를 배치할 때 사용

---

### yaml 파일을 통한 관리

- 모든 쿠버네티스 오브젝트는 yaml 파일로 export 가능
- yaml 파일을 통해 쿠버네티스 오브젝트를 생성, 수정, 삭제 가능

```bash

k get pod busybox -o yaml > busybox.yaml

k apply -f busybox.yaml

```

### yaml naming rule

{app}-{opt}-{obj}.yaml

### service yaml 예제

```yaml
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app.kubernetes.io/name: MyApp
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 9376
    - name: https
      protocol: TCP
      port: 443
      targetPort: 9377
```

## References

- 24단계 실습으로 정복하는 쿠버네티스 3,4장
