### DISCUSSION TITLE
ch5, ch6

### DISCUSSION THREAD

**Discussion by YONGHYNG** [studykuberstep24/studykuberstep24#32] [용학]
### 📌 쿠버네티스 작업 순서

- **Apply → Get → Describe → Logs → Get Event**
    1. YAML 파일을 이용해 오브젝트 생성(apply)하고 오브젝트 리스트는 get 명령어 확인
    2. 만약 파드가 정상적으로 생성되지 않으면 상세한 설정 정보를 describe 명령어 확인
    3. 애플리케이션 관련 에러는 로그 명령어(logs)로 확인하고, 쿠버네티스 클러스터 관련 메시지는 이벤트 명령어(get event)로 확인

### ✅ ImagePullBackOff 오류

![image.png](attachment:0ed8a7fb-696f-4a20-8d19-4729a72bc27b:image.png)

- kubectl apply -f https://raw.githubusercontent.com/wikibook/kubepractice/main/ch05/nginx-error-pod.yml
- kubectl get pod -o wide
- 이미지를 가져오는데 실패했다는 오류

**1-2. 상세 정보 확인**

![image.png](attachment:f7c8e6fb-0189-44ad-98be-b27c43739b4d:image.png)

- 파드를 실행했는데 에러가 발생하면 추가로 상세한 정보 확인 필요
- kubectl describe pod nginx-19

**1-3. 삭제 후 재배포 및 조회**

![image.png](attachment:f535ac00-239a-4767-9bbb-cb61b752b33f:image.png)

- kubectl delete pod nginx-19 #파드 삭제
- kubectl apply -f nginx-modify-pod.yml #수정 재배포
- kubectl get pods #조회

**1-4. 로그 확인 명령어**

- kubectl logs -f nginx-19
- kubectl logs -l component=kube-apiserver -n kube-system

**1-5. 전체 클러스터 레벨 에러 확인**

![image.png](attachment:cbb55bec-5338-47a3-8be3-99185bf7528c:image.png)

- kubectl get events

![image.png](attachment:f44ca259-7a01-4bac-b453-27d43fa98f0e:image.png)

- kubectl get events -n kube-system #-n 옵션으로 네임스페이스 지정 가능
- kubectl get events -A #전체 네임스페이스 이벤트 확인

### ✅ 장애 처리 사례 - 호스트 노드의 파일 시스템 용량 초과

![image.png](attachment:ffac3697-23a4-4158-af15-493fa07aaee9:image.png)

**2-1. 10개의 파드 각 노드에 분배**

![image.png](attachment:ae8291ab-cea3-4696-b6cc-014b1fc72dd9:image.png)

![image.png](attachment:efb56e59-cb4e-40dc-8c90-fe8b33053025:image.png)

- kubectl apply -f busybox-deploy.yml #10개의 파드가 각 노드에 고르게 분배
- kubectl get pod -o wide #조회

**2-2. 에러 발생**

- ssh [spkr@172.17.29.62](mailto:spkr@172.17.29.62) #2번 노드에 과부하 발생 만들기
- df -h #조회
- fallocate -l 30g 30g-file #원하는 특정 용량의 파일을 생성하는 리눅스 명령어 fallocate
- df -h #조회
- kubectl get pod -o wide -w #조회
- kubectl get events #이벤트 조회
- kubectl descrive node ubun20-02 #모든 리소스 상세하게 조회

**2-3. 실습 완료 후 삭제**

- kubectl delete deployments.apps busybox
- ssh spkr@ubun20-02
- rm 30g-file

## 📌 헬름 기반으로 애플리케이션 설치

- 다양한 리소스를 각자 관리하지 않고 하나의 패키지로 관리하는 도구가 헬름
- 리눅스 환경에서 yum, apt 등이 애플리케이션에 필요한 모든 라이브러리 패키지를 제공하는 것과 유사
- 헬름 차트, 헬름 리포지토리, 헬름 템플릿을 이해하고 실습해야 함

### ✅ 헬름의 주요 구성 요소, 헬름 차트, 헬름 리포지토리, 헬름 템플릿

**3-1. 헬름차트**

- 애플리케이션 설치에 사용되는 네트워크, 스토리지, 보안과 관련된 여러 쿠버네티스 리소스를 묶어놓은 패키지

![image.png](attachment:46f3ea32-bfc3-4f77-9eb3-3c20e29b6249:image.png)

**3-2. 헬름 리포지토리**

- 다양한 헬름 차트를 저장하고 공유하는 저장소
- 리눅스 패키지 관리 도구인 yum의 리포지토리와 동일한 기능
- helm repo list
- helm search repo bitnami #각 리포지토리별로 지원하는 애플리케이션 목록 확인

![image.png](attachment:670a1422-f6a0-4a30-a33d-b2f6fb37d0f6:image.png)

**3-3. 템플릿**

- 헬름은 템플릿을 사용해 설치와 관련된 파일 관리
- 일정한 형식 또는 포맷을 의미, 사용자는 이름, 날짜 등의 변수만 수정하면 해당 파일 사용 가능
- 헬름은 여러 템플릿 파일에서 공통으로 사용하는 변수를 단일 values.yaml 파일에서 관리
- 해당 파일만 수정하며 전체 템플릿 파일에서 해당 변수를 공통으로 적용 가능

### ✅ 헬름 차트를 이용한 NGINX 웹서버 설치

- `helm repo add`
    
    애플리케이션 설치에 사용하는 헬름 리포지토리를 로컬 환경에 추가
    
- `helm pull`
    
    헬름 차트 파일을 로컬호스트로 내려받음
    
- `cp values.yaml my-values.yaml`
    
    기존 헬름 차트 값 파일의 여러 값을 편집하기 위해 원본 파일(`values.yaml`)을 새로운 파일(`my-values.yaml`)로 복사
    
    새롭게 생성한 파일에서 필요한 옵션을 수정
    
- `helm install (helm 이름) -f my-values.yaml`
    
    수정한 파일을 템플릿 옵션 파일로 지정해 원하는 애플리케이션을 설치
    
- `helm ls`
    
    설치된 헬름 차트 목록을 확인
    
- `helm get manifest`
    
    주로 디버깅 용도로 사용하며, 현재 실행 중인 헬름 차트의 전체 YAML 파일 목록 및 상세 설정을 확인 가능
    
- `helm upgrade`
    
    기존 헬름 차트의 변수 등을 수정해서 재배포
    
- `helm delete`
    
    헬름 차트를 삭제
    

**3-4. helm 유틸리티 설치**

![image.png](attachment:4ea35f42-10cf-4cef-a634-5ec93032721c:image.png)

- helm repo add bitnami https://charts.bitnami.com/bitnami #NGINX 헬름 차트를 포함하는 리포지토리를 로컬 호스트에 추가
- helm search repo nginx #헬름 차트 검색
- helm pull bitnami/nginx #헬름 차트 다운로드
- tar xvfx nginx-12.0.4.tgz
- rm -rf nginx-12.0.4.tgz
- mv nginx nginx-12.0.4
- cd nginx-12.0.4/
- ls templates #헬름 차트에 설치할 전체 쿠버네티스 목록 확인
- cp values.yaml my-values.yaml #헬름 템플릿 변수 파일 수정

![image.png](attachment:b708a13e-6940-4aba-a397-e747379ad9b6:image.png)

- kubectl create ns nginx #nginx 네임스페이스 생성
- kubectl ns nginx #네임스페이스 변경
- helm install nginx -f my-values.yaml #생성한 네임스페이스에 NGINX 헬름 차트 설치
- helm ls #헬름 차트 확인
- kubectl get pod -o wide — 전체 조회

**3-6. 리소스 Requests/Limits 이해**

1. 제한 사용량을 초과해서 메모리를 사용하면 해당 파드는 어떻게 될까?

![image.png](attachment:b7e8b440-9fd6-4569-88d9-c10c3c993eba:image.png)

- kubectl apply -f mem-limits01-pod.yml
- kubectl get pod
- kubectl delete pod memory-demo-1 #해당 파트 삭제

1. 메모리 제한 사용량을 초과하지 않게 메모리 부하를 실행하는 파드 실행

```yaml
예제 6.3 메모리 사용량 요구사항(Requests)을 설정한 파드(mem-requests01-pod.yml)

apiVersion: v1
kind: Pod
metadata:
  name: memory-demo-1
spec:
  containers:
  - name: memory-demo-1
    image: polinux/stress
    resources:
      requests:
        memory: "36i"
      limits:
        memory: "66i"
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "100M", "--vm-hang", "1"]

06. 예를 기반으로 애플리케이션 설치하기

nodeSelector:
  kubernetes.io/hostname: ubun20-01

spec.containers.resources.requests.memory: 36i
- 메모리 Requests를 36i로 설정합니다.

spec.containers.command: ["stress"]
- [STOOM] 메모리 부하를 주는 파드를 실행합니다.

spec.nodeSelector
- 테스트를 위해 특정 노드(ubun20-01)에 파드를 할당합니다.

```

1. 메모리 사용량(6Gi)를 초과하지 않게 메모리 부하를 실행하는 파드 실행

```yaml
예제 6.4 5500MB 용량의 메모리 부하를 실행하는 파드(mem-stress-pod.yml, mem-requests01-pod.yml)

apiVersion: v1
kind: Pod
metadata:
  name: memory-demo-2
spec:
  containers:
  - name: memory-demo-2
    image: polinux/stress
    resources:
      requests:
        memory: "36i"
      limits:
        memory: "66i"
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "5500M", "--vm-hang", "1"]
    nodeSelector:
      kubernetes.io/hostname: ubun

1부 _ 쿠버네티스의 개념과 설치, 기본 관리 방법

- spec.containers.resources.limits.memory: 66i
  메모리 제한 사용량을 66i로 설정합니다.

- spec.containers.command: ["stress"]
  5500M의 메모리 부하로 파드를 실행합니다.

```

- k apply -f mem-stress-pod.yml #메모리 부하를 발생시키는 파드 생성
- kubectl get pods #조회

1. 직접 파드에 접속해 메모리 사용량 증가
- kubectl exec -it memory-demo-1 — bash
- stress —vm 1 —vm-bytes 2900M —vm-hang 1 #메모리 부하를 증가하는 명령어
- kubectl get pod -w -o wide #상태 변화 확인
- kubectl delete pod -all #조회
- kubectl delete deployments.apps —all #
