### DISCUSSION TITLE
5,6장 k8s 트러블슈팅, helm 차트 기반 설치

### DISCUSSION THREAD

**Discussion by yjinheon** [studykuberstep24/studykuberstep24#33] [진헌]
### k8s 작업 순서

1. yaml -> apply로 object 생성
2. get으로 object 확인
3. describe로 object 상세 확인
4. logs로 pod log 확인
5. events로 object 이벤트 확인

### yaml -> apply로 object 생성

```bash

kubectl apply -f pod.yaml

```

**pod.yaml**

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox
  labels:
    app: busybox
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: busybox
    template:
      metadata:
        labels:
          app: busybox
      spec:
        containers:
          - name: busybox
            image: busybox
            command: ["sh", "-c", "echo Hello Kubernetes! && sleep 3600"]
```

**에러 생성**

- 임의의 디스크 관련 에러를 발생시키기 위해 30G 파일 생성

```bash

fallocate -l 30G 30G.file # 특정 용량의 파일 생성

```

### get으로 object 확인

- kubectl get은 특정 namespace의 결과만 보여줌

```bash

kubectl get pod

kubectl get pod --A # 모든 namespace의 pod 확인
```

### describe로 object 상세 확인

```bash

kubectl describe pod <pod-name>
```

### logs로 pod log 확인

```bash

kubectl logs <pod-name>

kubectl logs -f <pod-name> # 실시간 로그 확인
```

### events로 object 이벤트 확인

- 특정 어플리케이션 수준이 아닌 클러스터 수준의 이벤트를 확인

```bash

kubectl get events

```

---

**_Key Takeaway_**

- k8s에서의 트러블 슈팅 절차는 object 생성, 확인, 상세 확인, 로그 확인, 이벤트 확인이다.
- k8s에서는 자원이 부족한 노드가 발생하면 자동으로 해당 노드의 pod를 여유있는 노드로 이동시킨다.

---

## 2. Helm

---

**_Concept_**

- **Helm** : k8s의 패키지 관리자. k8s의 yaml 파일을 패키지화하여 배포 및 관리를 쉽게 할 수 있게 해준다. Helm Chart, Helm Repository, Helm Template으로 구성된다.
- **Helm Chart** : k8s 어플리케이션 설치에 사용되는 네트워크, 스토리지, 보안과 관련된 여러 k8s 리소스를 포함하는 패키지
- **Helm Repository** : Helm Chart를 저장하는 저장소
- **Helm Template** : Helm Chart를 템플릿화하여 사용자가 원하는 값으로 쉽게 변경할 수 있게 해준다.

---

### Helm Repository

```bash

# repository list 확인

helm repo list

# repository 내 설치 가능한 app list 확인

helm search repo bitnami

```

### Helm Template

- 여러 파일에서 공통적으로 쓰이는 변수를 values.yaml에 정의하여 사용
- values.yaml에 정의된 변수를 사용하기 위해 {{ .Values.<변수명> }} 형태로 사용
- values.yaml에 정의된 변수는 개별 리소스의 매니페스트 파일에 적용됨

### Helm 을 이욯한 어플리케이션 관리

```bash

# add repository

helm repo add bitnami https://charts.bitnami.com/bitnami

# pull

helm pull bitnami/nginx

# install

helm install my-nginx bitnami/nginx

# ls

helm ls

# manifest 확인

# 현재 실행중인 리소스의 전체 yaml 파일 목록 및 상세설정 확인

helm get manifest my-nginx

# 변수 등을 수정후 재배포

helm upgrade


```

### Request/Limit 설정

---

**_Concept_**

- **Request** : k8s에서 Request는 처음 노드에 자원을 할당할 때 Request이사의 여유자원이 있는 노드에 pod를 배치한다. pod는 Request에서 할당한 자원만큼 사용이 가능하도록 보장받음
- **Limit** : pod가 사용할 수 있는 최대 자원량을 설정. pod가 Limit을 초과하면 pod는 종료됨

---

## Reference

- 24단계 실습으로 정복하는 쿠버네티스 5, 6장
