### DISCUSSION TITLE
ch07. 쿠버네티스 서비스 사용하기

### DISCUSSION THREAD

**Discussion by vimkim** [studykuberstep24/studykuberstep24#43] [대현]
![image](https://github.com/user-attachments/assets/09faf3dd-4d22-43ae-9839-8eec7e11eacf)

---

```yaml
apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport-svc
  namespace: default
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    nodePort: 30080
  selector:
    app: nginx 
  type: NodePort

```

노드포트 서비스

![image](https://github.com/user-attachments/assets/de83319d-00ba-4706-8375-e3f387350a30)

---

![image](https://github.com/user-attachments/assets/9abc5e95-9f8e-4a7f-b667-c6b046be0b28)

![image](https://github.com/user-attachments/assets/495a09a4-d48d-403e-ac33-0e1b71859271)

---

### core dns

![image](https://github.com/user-attachments/assets/fd2a0f03-c405-4a18-82ff-f0c93c113142)

![image](https://github.com/user-attachments/assets/5ebe084a-bafb-4f1a-b232-ad5a4ca8c115)

---

![image](https://github.com/user-attachments/assets/46fc64a2-3a8e-4484-a836-2ccf398529dd)

minikube에서는 아무것도 안 나온다.

---

![image](https://github.com/user-attachments/assets/304f50d6-ac36-4d89-92b4-8239133898bd)

네임스페이스가 다르면 nslookup에 실패한다.

![image](https://github.com/user-attachments/assets/a31f1cda-40b6-42f1-98b1-41994bf66022)

뒤에 `.default`를 붙여주면 성공한다.

![image](https://github.com/user-attachments/assets/1912fc2c-a629-477c-8593-4c64361f1328)

nslookup도 전체를 다 적어주면 성공한다. 그냥 nginx-svc.default는 실패한다 (?).

---

### nodeport 적용

![image](https://github.com/user-attachments/assets/1d9bade6-8afb-4170-8aeb-ce2a7904f2c8)

![image](https://github.com/user-attachments/assets/077c9ae3-11f6-4902-accb-d5083919a29d)

외부에서 30080 포트로 접속 성공

---

### kube-proxy ipvs

![image](https://github.com/user-attachments/assets/a08bed96-a417-4344-bdfb-60847bbb1ff2)

ipvs는 클러스터 IP 서비스와 연동해서 CLUSTER-IP로 요청하는 연결을 내부의 파드로 전달하는 역할을 함.

![image](https://github.com/user-attachments/assets/a0e39660-f1dc-4389-8679-0ef6f05ca47c)

---

> minikube에서 ipvsadm으로 policy 확인하는 방법?
