### DISCUSSION TITLE
ch10. 쿠버네티스 스토리지

### DISCUSSION THREAD

**Discussion by vimkim** [studykuberstep24/studykuberstep24#67] [대현]
## OpenEBS 로컬 호스트패스 설치

![image](https://github.com/user-attachments/assets/60ab57a3-1086-463f-9a0b-e4212e86041e)

### 나의 요약
 
openebs-device와 openebs-hostpath라는 2가지 스토리지 클래스가 생성되었다.

openebs-device는 노드에서 마운트하지 않은 별도의 디스크 디바이스 등에 파드의 데이터를 저장한다.

openebs-hostpath는 호스트 노드의 특정 디렉터리에 데이터를 할당하는 방식이다.

기본은 /var/openebs/local

별도 호스트 노드의 파일 시스템 용량에 영향을 끼치지 않도록 별도의 마운트 포인트를 사용하는 것을 권장.

---

### 지피티 문의

지피티 이게 뭔 소리야? 이해가게 설명해줘.

---

### 💡 **openebs는 Kubernetes에서 사용하는 스토리지 시스템이야.**
Kubernetes는 기본적으로 컨테이너를 실행하지만, 컨테이너가 꺼졌다 켜지면 데이터가 사라질 수 있어. 그래서 **Persistent Volume (PV)** 라는 방식으로 데이터를 안전하게 저장해야 하는데, 그걸 도와주는 게 **OpenEBS** 같은 스토리지 솔루션이야.

---

#### 1. **openebs-device**
- **노드(서버)에 연결되어 있지만 아직 아무 데도 마운트하지 않은 디스크**를 사용해.
- 예: 서버에 SSD를 하나 꽂았는데 아직 포맷도 안 하고 마운트도 안 했을 때, 이걸 openebs-device가 자동으로 감지해서 거기에 파드 데이터를 저장해줄 수 있어.
- 이 방식은 **기존 시스템 디스크를 건드리지 않아서 안전**하고 성능도 좋아.

#### 2. **openebs-hostpath**
- 말 그대로 **호스트 머신(노드)의 디렉터리**를 그냥 파드의 저장소로 써.
- 기본 경로는 `/var/openebs/local`
- 이건 별도 디스크 없이 간단히 쓸 수 있지만, 주의할 점이 있어:
  - **노드의 메인 디스크 공간**을 쓰기 때문에, 용량이 부족하면 시스템 전체에 영향을 줄 수 있어.

---

### 🔸 그래서 권장하는 방식은?
**hostpath 쓸 거면, /var/openebs/local 같은 기본 디렉터리를 쓰지 말고,**
**별도의 디스크를 마운트한 디렉터리로 바꿔서 사용하라는 얘기야.**

예를 들어:
```bash
mount /dev/sdb1 /mnt/openebs
```

그리고 `/mnt/openebs`를 hostpath 스토리지 경로로 설정하면,
메인 디스크가 아니라 `/dev/sdb1`에만 데이터가 저장되니까 시스템에도 안전하고 관리하기도 좋아.

> 아하!!!!!!

---

## 03 스토리지 클래스를 이용한 PVC 및 영구볼륨 사용

이번 작업은 사용자가 가장 많이 하는 작업이다.

YAML을 이용해 PVC를 생성하고 영구 볼륨을 마운트하는 실습입니다.

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: default-pvc
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce  
  resources:
    requests:
      storage: 1Gi
  storageClassName: "openebs-hostpath"
```

음... 책의 설명도 좋지만 좀 더 보기 편하게 지피티야 도와줘!

---

물론이죠! 이 YAML 파일은 **Kubernetes**에서 사용하는 설정 파일 중 하나로, **PersistentVolumeClaim (PVC)** 를 정의하고 있어요. 아래에 쉽게 설명해 드릴게요.

---

### 🔍 이게 뭔가요?
이 설정은 Kubernetes에서 **"나 이만큼 저장 공간 필요해요!"** 하고 요청하는 거예요.  
PVC는 Kubernetes에서 **디스크 공간을 요청하는 방법**이에요.

---

### 🧩 주요 구성 요소 설명:

```yaml
apiVersion: v1
```
- 사용하는 Kubernetes API 버전이에요.

```yaml
kind: PersistentVolumeClaim
```
- 이 파일은 **PersistentVolumeClaim (PVC)** 를 정의하고 있다는 뜻이에요.

```yaml
metadata:
  name: default-pvc
  namespace: default
```
- PVC의 이름은 `default-pvc`이고, `default` 네임스페이스 안에서 사용된다는 뜻이에요.

```yaml
spec:
  accessModes:
  - ReadWriteOnce  
```
- **ReadWriteOnce**: 이 저장소는 **한 개의 노드에서만 읽고 쓰기 가능**하다는 뜻이에요.

```yaml
  resources:
    requests:
      storage: 1Gi
```
- 이 PVC는 **1GiB(기가바이트)** 만큼의 저장 공간을 요청하고 있어요.

```yaml
  storageClassName: "openebs-hostpath"
```
- 저장소를 **어떻게 만들지**에 대한 정보에요.
- 여기서는 `"openebs-hostpath"`라는 **스토리지 클래스**를 사용해서 볼륨을 만들겠다는 의미예요.

---

![image](https://github.com/user-attachments/assets/134bf157-d1f9-42ca-a803-bcc242eeff38)

실행을 했더니 위와 같이 waiting for first consumer to be created before binding 이 나타났다!

파드가 생성되고 해당 PVC를 마운트하면 상태가 Bound로 변경된다.

이렇듯, 사용자는 먼저 파드가 사용할 볼륨을 PVC로 생성한다. 이후 해당 PVC를 YAML의 volumeMounts와 volumes에 추가해서 사용한다.

---

### PVC를 사용하는 deployment yaml 예제

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: date-pod
  namespace: default
  labels:
    app: date
spec:
  replicas: 1
  selector:
    matchLabels:
      app: date
  template:    
    metadata:
      labels:
        app: date
    spec:
      containers:
      - name: date-pod
        image: busybox
        command:
        - "/bin/sh"
        - "-c"
        - "while true; do date >> /data/pod-out.txt; cd /data; sync; sync; sleep 30; done"
        volumeMounts:  
        - name: date-vol  # Volume 이름
          mountPath: /data  # Mount 이름 
      volumes:  # 어떤 Volume을 사용할 것인지
      - name: date-vol
        persistentVolumeClaim:
          claimName: default-pvc
```

지피티야 쉽게 설명해줘

---

물론이죠! 이 `Deployment` YAML 파일은 Kubernetes에서 **"date-pod"**라는 이름의 **Pod**를 생성하고 실행하는 설정입니다. 주요 내용을 쉽게 풀어서 설명해볼게요.

---

### 📦 목적:
- `busybox`라는 간단한 Linux 도구를 이용해서,
- 30초마다 현재 날짜/시간을 파일에 계속 저장하는 Pod를 만들어요.

---

#### `apiVersion: apps/v1`
- 이 배포 설정이 Kubernetes의 **앱(Deployment)** 리소스를 위한 것이란 뜻이에요.

#### `kind: Deployment`
- **Deployment**는 Pod를 관리해주는 역할을 해요. Pod가 꺼지면 다시 띄워주고, 원하는 수만큼 유지해줘요.

#### `metadata`
- 이름(`name: date-pod`)과 레이블(`labels: app: date`) 같은 정보를 담아요.

#### `spec` (Deployment의 본체)
- `replicas: 1` → Pod를 1개만 실행하겠다는 의미예요.
- `selector` → 어떤 Pod가 이 Deployment에 해당하는지 **레이블로 찾는 기준**이에요.
- `template` → 실제로 **어떤 Pod를 만들지** 정의해요.

---

### 🧪 Pod 내부 설명:

```yaml
containers:
- name: date-pod
  image: busybox
```

- 컨테이너 이름은 `date-pod`이고,
- 사용하는 이미지는 `busybox`예요 (작고 빠른 리눅스 유틸 도구 모음)

```yaml
command:
- "/bin/sh"
- "-c"
- "while true; do date >> /data/pod-out.txt; cd /data; sync; sync; sleep 30; done"
```

- 이건 컨테이너 안에서 실행할 명령어예요.
- `date >> /data/pod-out.txt` → 현재 날짜를 `/data/pod-out.txt` 파일에 추가로 기록해요.
- `sync; sync;` → 데이터가 디스크에 실제로 저장되도록 보장해요.
- `sleep 30` → 30초 쉬고 다시 반복해요.

```yaml
volumeMounts:
- name: date-vol
  mountPath: /data
```

- `/data`라는 폴더를 외부 저장공간(볼륨)과 연결해요.

---

### 💾 저장공간 설정

```yaml
volumes:
- name: date-vol
  persistentVolumeClaim:
    claimName: default-pvc
```

- 이 Pod는 `default-pvc`라는 이름의 **Persistent Volume Claim**(PVC)을 사용해서 데이터를 저장해요.
- PVC는 디스크처럼 사용할 수 있어서, **Pod가 죽거나 재시작해도** 기록이 남아요!

---

### 📌 정리하면?

이 설정은 Kubernetes에 아래와 같은 Pod을 만들어요:

- 30초마다 날짜를 `/data/pod-out.txt` 파일에 저장
- 이 파일은 외부 저장소(PVC)를 써서 **데이터가 유지됨**
- Pod는 꺼져도 Deployment가 자동으로 다시 실행시켜 줌

---

이전과 다르게 데이터가 사라지지 않고 영구볼륨에 보관.

PVC 볼륨을 사용하는 YAML은 기존과 동일하고, 오직 volumeMounts와 volumes 부분만 기존 디플로이먼트 YAML 파일에 추가.

![image](https://github.com/user-attachments/assets/51fde561-e9c0-4a86-a7db-98416cab8fd0)

성공!

---

### pod 삭제

![image](https://github.com/user-attachments/assets/efcdcbd4-0b3d-4513-818e-592f76f95cf6)

지워도 다시 살아나고, PVC에 자동으로 붙는다!

---

### pvc 삭제

![image](https://github.com/user-attachments/assets/95c1d298-f4aa-4090-8b17-52503627c4b2)

Delete: PVC를 삭제하면 PV도 삭제됨.
Retain: PVC를 삭제해도 영구볼륨은 유지됨. 나중에 수동으로 PVC를 생성할 수 있음.

OpenEBS 기본 정책은 Delete.

![image](https://github.com/user-attachments/assets/9b56796f-e91c-4967-b9e1-5b62cbd35ff8)

---

## 04 사용자 스토리지 클래스를 지정해 헬름 차트 MySQL 설치하기

스토리지 클래스도 헬름 템플릿 파일을 이용해 지정할 수 있음.
대부분의 헬름 파일에 스토리지 클래스만 지정하면 PVC가 자동 생성.

![image](https://github.com/user-attachments/assets/4ea6c700-3fea-45a9-a3f2-1878eea5bc3d)

![image](https://github.com/user-attachments/assets/dfaa170c-46de-4700-b47c-f5357918ec2b)

---

### helm 으로 설치된 pvc 삭제

![image](https://github.com/user-attachments/assets/9d865335-a8de-4ad8-90f2-5e72a794fd8c)

남아있기 때문에 수동으로 삭제해야 한다.

---

05 로컬 호스트패스 스토리지 클래스의 장점 및 제약 사항

장점: 네트워크 전송에 따른 추가 지연이 없다. 성능이 월등하다.

단점: 해당 노드에서만 파드가 실행된다. 노드가 다운되면 파드 역시 사용하지 못한다.

---

### 노드 제거 테스트

생략

---

## 개인적인 궁금증

![image](https://github.com/user-attachments/assets/a7a9ad96-b9a1-4942-ba23-e2a7dd4ec4c6)

위 사진은 OpenEBS를 설치하고 난 이후

```bash
$ k get all -A
```

위와 같은 명령을 실행한 모습이다.

각각은 뭘하는 걸까?

---

#### `kube-system` 네임스페이스 (Kubernetes 자체를 운영하는 컴포넌트들)
- `etcd-minikube`: **Kubernetes의 데이터 저장소(DB)** 역할을 함. 클러스터 상태 정보가 여기에 저장됨.
- `kube-apiserver-minikube`: **Kubernetes API 서버**. kubectl 같은 툴이 이 서버를 통해 클러스터와 소통함.
- `kube-controller-manager-minikube`: 클러스터 상태를 감시하고, 필요시 리소스를 생성/삭제하는 **컨트롤러 모음**.
- `kube-scheduler-minikube`: 새로 생성된 pod들을 어떤 노드에 배치할지 결정하는 **스케줄러**.
- `kube-proxy-djwh6`: 각 노드에서 **서비스 트래픽을 적절한 Pod으로 전달**해주는 네트워크 프록시.

#### `openebs` 네임스페이스 (OpenEBS 스토리지 관련 컴포넌트들)
- `openebs-localpv-provisioner`: **로컬 디스크 기반의 볼륨을 자동으로 생성해주는 역할**을 하는 프로비저너.
- `openebs-ndm`: **Node Disk Manager**. 노드의 디스크 정보를 수집하고 관리하는 에이전트 (아직 ContainerCreating 상태).
- `openebs-ndm-cluster-exporter`: NDM의 상태나 통계를 **Prometheus로 노출**하기 위한 exporter.
- `openebs-ndm-node-exporter`: 노드의 디스크 메트릭을 **Prometheus와 같은 모니터링 툴에 노출**함.
- `openebs-ndm-operator`: 전체 NDM 관련 자원들을 **관리**하는 operator. (컨트롤러처럼 동작)

---

### 2. **Services (Pod과 외부/내부 간 통신을 위한 접근 경로)**

- `service/kubernetes`: Kubernetes API 서버에 접근할 수 있는 **클러스터 내부 IP**.
- `openebs-ndm-cluster-exporter-service`: 클러스터 exporter를 **내부에서 접근** 가능하게 해주는 서비스.
- `openebs-ndm-node-exporter-service`: node exporter용 서비스. 마찬가지로 **내부 통신** 용도.

---

### 3. **DaemonSets (노드마다 하나씩 Pod을 배포)**

- `kube-proxy`: 앞서 본 pod와 동일. **모든 노드에 설치**되어야 함.
- `openebs-ndm`: NDM도 **각 노드에서 디스크를 탐색**해야 하므로 DaemonSet으로 배포.
- `openebs-ndm-node-exporter`: 이 역시 **모든 노드에서 디스크 상태를 수집**하기 위한 DaemonSet.

---

### 4. **Deployments (Pod을 관리하는 컨트롤러)**

- 각종 OpenEBS 컴포넌트 (`localpv-provisioner`, `ndm-cluster-exporter`, `ndm-operator`)를 **자동 복구**, **업데이트**, **확장/축소** 가능하게 관리함.

---

### 5. **ReplicaSets (Deployment가 실제로 Pod 개수를 맞추는 수단)**

- Deployments와 1:1로 연결되어 있고, **원하는 개수만큼 Pod이 유지되도록 보장**함.

---

### 요약
| 컴포넌트 종류 | 설명 |
|---------------|------|
| `kube-system` Pods | Kubernetes 자체를 운영하는 핵심 시스템들 |
| `openebs` Pods | 스토리지 관련 기능 제공 (디스크 탐색, 로컬 볼륨 생성 등) |
| Services | 내부 통신을 위해 Pod 앞에 세워진 접근 포인트 |
| DaemonSets | 모든 노드에 필수 Pod 배포 |
| Deployments | 특정 앱을 안정적으로 유지·관리 |
| ReplicaSets | 실제 Pod 수를 컨트롤 (Deployment의 하위 개념) |

---
