### DISCUSSION TITLE
ch09. Traefik을 이용한 쿠버네티스 인그레스 구축

### DISCUSSION THREAD

**Discussion by YuDeokRin** [studykuberstep24/studykuberstep24#70] [덕린]
# Traefik을 이용한 쿠버네티스 인그레스 구축

- 일반적으로 인그레스의 뜻은 입장하자, 들어가다의 뜻을 갖고 있다.
- IT 분야에서는 인그레스가 외부에서 내부로 들어가는 네트워크를 의미한다.
- 쿠버네티스 인그레스는 외부의 HTTP 요청에 대한 서비스 처리 규칙을 정의한 리소스이다.
- 관리자는 SSL/TLS 인증서 등 외부 접속에 관한 규칙을 애플리케이션 설정에서 분리해서 별도의 인그레스 리소스로 관리 → 애플리케이션 설정이 편리 해짐.

- 쿠버네티스는 인그레스(Ingress)라는 별도의 오브젝트로 네트워크 레이어7 기능을 제공합니다.

> 참고. 
인그레스의 반대개념은 내부에서 외부로 나가는 것을 말하며 이그레스(Egress)라고한다.
> 

### ➡️ 인그레스의 주요기능

1. URL 및 경로별 백엔드 서비스 분리
2. SSL/TLS 인증서 연동
3. 애플리케이션 관리 효율을 위해 외부 접속에 관한 상세 규칙을 별도 인그레스 리소스로 분리

### ➡️ L7 스위치란?

- L7 스위치는 OSI 7계층 중 **Application Layer(7계층)** 에서 동작하는 스위치 또는 로드밸런서를 말함.
- 보통 우리가 말하는 **HTTP, HTTPS, SMTP, FTP** 같은 프로토콜 수준에서 트래픽을 분석하고 제어함.
- 즉, 단순히 IP, 포트로만 구분하는게 아니라 **URL, Cookie, Header, Host** 등의 내용까지 보고 트래픽을 분기시킴.

### ✅ 실습과제

```
1. 헬름을 이용해 인그레스 컨트롤러인 Traefik 을 설치합니다.
2. 인그레스의 백엔드 분리 기능을 확인하기 위해 4 개의 서로 다른 디플로이먼트 및 서비스를 설치합니다.
3. Traek 인그레스 설정을 검증합니다.
A. 가상 호스트 및 경로로 4 가지 서비스를 분기
	coffee.myweb.com
	tea.myweb.com
	www.myweb.com/juice
	www.myweb.com/water
B. SSL/TLS 인증서 적용
```

## 1️⃣ Traefik 인그레스 컨트롤러 설치

- 인그레스 컨트롤러는 쿠버네티스 자체에서 제공하지 않는다. 따라서 NGINX, haproxy, traefix 등 별로의 솔루션을 사용해야한다.
- 가장 많이 사용하는 솔루션 → NGINX 인그레스 컨트롤러
- 하지만 NGINX가 제공하지 않는 관리자 페이지를 제공하는 전용 CRD를 이용해 옵션 설정이 쉽고 사례가 풍부한 Traefik을 실 서비스에 사용하고 있다고 Traefik를 쓴다고한다.

### ✅ Traefik 설치

```bash
# Tradfik 설치 
❯ helm repo add traefik https://helm.traefik.io/traefik
"traefik" has been added to your repositories

# 리스트 확인(다운로드) 
❯ helm repo list
NAME   	URL
bitnami	https://charts.bitnami.com/bitnami
traefik	https://helm.traefik.io/traefik
```

- 파일 복사  : my-values.yaml

```bash
❯ cp values.yaml my-values.yaml
```

- deployment.replicas
    - Traefik 파드 장애에 대비해 파드를 이중화합니다.

- ports.traefik.expose
    - Traefik 관리자 페이지를 외부에 접속 가능하도록 설정

- affinity.podAntiAffinity
    - 같은 노드에 tradfik 파드가 추가 실행되지 않도록 affinity 설정을 한다.
    - 먼저 affinity의 ‘{ }’ 설정을 지운다. 다음 기본 템플릿 파일 오류로 ‘values: - traekfik’ 부분을 별도로 추가합니다.

### ➡️ Traefik용으로 별도의 네임스페이스 만들고 설치 진행

```bash
❯ kubectl create ns traefik
namespace/traefik created

❯ kubectl ns traefik
Context "minikube" modified.
Active namespace is "traefik".
```

## 2️⃣ 인그레스 테스트용 애플리케이션 설치

- 인그레스의 주요 용도는 사용자의 URL 경로에 따라 백엔드 웹서버를 구분해서 응답하는 것이다.
    - 예) www.myweb.com/products와 auth.myweb.com/services 등으로 사용자가 접속하는 URL과 하위 경로가 다르면 서로 다른 웹서버에서 응답하도록 설정할 수 있다.

- 테스트를 위해 서로 다른 4개의 디플로이먼트와 서비스를 생성. 이미지로 ‘image:nginxdemos/nginx-hello:plain-text’를 사용한다. 이 NGINX 이미지는 서비스 호출 시 각각의 호스트네임을 응답하므로 개별 요청을 구분하기가 쉽다.

```yaml
# coffee Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coffee
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: coffee
  template:
    metadata:
      labels:
        app: coffee
    spec:
      containers:
        - name: coffee
          image: nginxdemos/nginx-hello:plain-text
          ports:
            - containerPort: 8080
---
# coffee Service
apiVersion: v1
kind: Service
metadata:
  name: coffee-svc
  namespace: default
spec:
  selector:
    app: coffee
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
---
# tea Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tea
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tea
  template:
    metadata:
      labels:
        app: tea
    spec:
      containers:
        - name: tea
          image: nginxdemos/nginx-hello:plain-text
          ports:
            - containerPort: 8080
---
# tea Service
apiVersion: v1
kind: Service
metadata:
  name: tea-svc
  namespace: default
spec:
  selector:
    app: tea
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
---
# juice Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: juice
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: juice
  template:
    metadata:
      labels:
        app: juice
    spec:
      containers:
        - name: juice
          image: nginxdemos/nginx-hello:plain-text
          ports:
            - containerPort: 8080
---
# juice Service
apiVersion: v1
kind: Service
metadata:
  name: juice-svc
  namespace: default
spec:
  selector:
    app: juice
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
---
# water Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: water
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: water
  template:
    metadata:
      labels:
        app: water
    spec:
      containers:
        - name: water
          image: nginxdemos/nginx-hello:plain-text
          ports:
            - containerPort: 8080
---
# water Service
apiVersion: v1
kind: Service
metadata:
  name: water-svc
  namespace: default
spec:
  selector:
    app: water
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http

```

- kind : Deployment, Service
    - 서로 다른 4개의 디플로이먼트, 서비스 파일을 생성한다. 4개의 파일을 디플로이먼트 이름, 컨테이너 이름, 이미지 이름, 서비스 이름, 셀렉터 키-값 만 변경해서 생성한다.

- 작성한 YAML 파일로 4개의 디플로이먼트와 서비스를 생성한다.

```yaml
## default 네임스페이스에서 실행합니다.
[spkr@erdia22 ch09 (ubun01:traefik)]$ k ns default
Context "ubun01" modified.
Active namespace i s "default".

##chog 디렉터리에서 'Cafe-svc-deploy.yml 파일을 확인할 수 있습니다.
[spr@erdia22 traefik-10.21.1 (ubun01: traefik)]$ cd . .
[spkr@erdia22 ch09 (ubun01:default)]$ k apply - f cafe-svc-deploy.yml

## 이전 테스트에 사용한 nginx-hello 디플로이먼트와 busybox 파드를 삭제합니다.
[spkr®erdia22 ch09 (ubun01:default)]$ k delete deployments.apps nginx-hello
[spkr@erdia22 ch09 (ubun01:default)]$ k delete pod busybox

## 새롭게 설치한 파드와 서비스를 확인할 수 있습니다.
[spr@erdia22 ch09 (ubun01:default)]$ k get pod, svc
NAME                         READY STATUS  RESTARTS  AGE
pod/cof fee-7b9b4bbd99-6hsd1 1/1   Running 0         5m28s
(생략)
```

- 별도의 busybox 파드를 실행해 개별 서비스 이름으로 접속 테스트를 한다. 각 서비스 이름(coffee-svc)에 해당하는 파드(coffee)가 자신의 호스트네임(파드이름)을 응답하는 것을 확인할 수 있다.

```yaml
[spkr@erdia22 ch09 (ubun01:default)]$ k run busybox --image=busybox:1.28 --restart=Never
--sleep 1d
pod/busybox created
[spkr@erdia22 ch09 (ubun01:default)]$ k exec -it busybox --sh
/ # wget -0- coffee-svc
(생략)
Server name: coffee-7b9b4bbd99-6hsd1
/ # wget -0- water-svc
(생략)
Server name: water-565ff89485-kbfg2
/ # exit
```

## 3️⃣ Traefik 인그레스 설정 테스트

- 가상 호스트와 URL 경로에 따른 서비스 분기와 사용자 지정 SSL/TLS 인증서 사용을 알아보자.

- 인그레스 설정 그림 예시)

<img width="600" alt="image 1" src="https://github.com/user-attachments/assets/8ed1dcd2-133b-45d9-804b-aa36ba1ba62f" />

- 그림과 같이 서로 다른 URL(coffee.myweb.com, tea.myweb.com)과 서로 다른 경로(www.myweb.com/juice, www.myweb.com/water)에 대해 각각 인그레스 설정을 통해 서로 다른 웹서버가 응답하도록 설정하다.

- Traefik 인그레스 설정 파일은 IngressRoute라는 자체 CRD(Custom Resource Definition) 쿠버네티스 리소스를 사용한다.
- CRD란 사용자가 임의로 자신이 필요한 쿠버네티스 API 리소스를 모아서 원하는 기능을 구현하는 쿠버네티스 API 확장 기능이다.
- Traefik은 사용자가 편리하게 인그레스 기능을 구현할 수 있도록 자체적으로 IngressRoute라는 CRD를 제공한다. 여기서는 이 IngressRoute CRD를 이용해 서로 다른 4개의 서비스(coffee, tea, juice, water)로 분리하는 인그레스 제공

### ➡️ 가상 호스트와 URL 경로에 따른 서비스 분기

- 실습으로 IngressRoute CRD 설정을 알아보자.

- IngressRoute에 대한 YAML 파일 예제
    - `apiVersion`
        - 기존 파스, 디플로이먼트 API 버전과 다르게 사용자 지정 API 버전을 사용
    - `kind`
        - 오브젝트 이름은 IngressRoute 이다.
    - `spec.entryPoints: web`
        - Traefik의 entryPoints(진입점)는 Traefik에서 처리하는 트래픽을 의미한다. 해당 트래픽이 라우팅 과정을 거쳐서 쿠버네티스 서비스로 전달된다.
    - `spec.routes.match: Host(’coffee.myweb.com’)`
        - entryPoints에 전달되는 트래픽 중 ‘coffee.myweb.com’이라는 가상 호스트를 가진 트래픽만 처리한다는 설정이다.
    - `spec.route.services.name: coffee-svc`
        - 해당 entryPoints와 route에 해당하는 트래픽을 ‘coffee-svc’이라는 이름을 가진 서비스로 전달하는 설정이다.

```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: coffee-ingressroute
  namespace: default
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`coffee.myweb.com`)
      kind: Rule
      services:
        - name: coffee-svc
          port: 80
(생략)
```

- EntryPoints, Routes, Services와의 관계를 그림으로 나타내면 다음과 같음
    - 엔트리 포인트가 라우트를 거쳐서 개별 서비스에 전달된다.

<img width="600" alt="image 1" src="https://github.com/user-attachments/assets/dc2d1f96-4fde-453b-b0b7-9771b111551a" />

- 같은 설정으로 3개의 IngressRoute를 추가한다.
- 설정은 동일하고 entryPoints와 routes, tls부분만 변경한다.

```yaml
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host("www.myweb.com") && PathPrefix('/juice')
      tls:
        certResolver: myresolver
```

- spec.entryPoints: websecure
    - 앞서 설정과 다르게 SSL/TLS 인증서 기반의 암호화 통신 설정을 추가했습니다.
- spec.routes.match: Host('www.myweb.com') & PathPrefix(/juice')
    - 가상 호스트 www.myweb.com 의 '/juice' URL 경로의 트래픽만 처리합니다.
- spec.tls.certResolver: myresolver
    - Traetik 은 기본 설정으로 인증서를 제공합니다. 'lets-enctypt 6 인증서를 사용합니다.
