### DISCUSSION TITLE
ch09 쿠버네티스 인그레스 구축, ch10 쿠버네티스 스토리지

### DISCUSSION THREAD

**Discussion by yjinheon** [studykuberstep24/studykuberstep24#71] [진헌]
### Minikube Cluster

- minikuke cluster 구축용 스크립트

```bash

#!/bin/bash

######################
# Create The Cluster #
######################

minikube start \
  --cpus 3 \
  --memory 6900 \
  --nodes 3
#--disk-size 10g

minikube addons enable ingress


```

### Traefik Namespaces

```bash

kubectl create namespace traefik

```

```yaml
affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: app.kubernetes.io/name
              operator: In
              values:
                - traefik
                - '{{ template "traefik.name" . }}'
            - key: app.kubernetes.io/instance
              operator: In
              values:
                - '{{ .Release.Name }}-{{ include "traefik.namespace" . }}'
                - traefik
        topologyKey: kubernetes.io/hostname
```

- dashboard enabled `true` 로 변경

```yaml
ingressRoute:
  dashboard:
    # -- Create an IngressRoute for the dashboard
    enabled: true
    # -- Additional ingressRoute annotations (e.g. for kubernetes.io/ingress.class)
    annotations: {}
    # -- Additional ingressRoute labels (e.g. for filtering IngressRoute by custom labels)
    labels: {}
    # -- The router match rule used for the dashboard ingressRoute
    matchRule: PathPrefix(`/dashboard`) || PathPrefix(`/api`)
    # -- The internal service used for the dashboard ingressRoute
    services:
      - name: api@internal
        kind: TraefikService
    # -- Specify the allowed entrypoints to use for the dashboard ingress route, (e.g. traefik, web, websecure).
```

- Minikube로 로컬에 실행할 경우 NodePort로 hostPort를 열어야 한다.

```yaml
service:
  enabled: true
  ## -- Single service is using `MixedProtocolLBService` feature gate.
  ## -- When set to false, it will create two Service, one for TCP and one for UDP.
  single: true
  #type: LoadBalancer
  type: NodePort
  # -- Additional annotations applied to both TCP and UDP services (e.g. for cloud provider specific config)
```

### IngressRoute

- IngressRoute실습을 위한 환경구축

![image](https://github.com/user-attachments/assets/94ab6e57-a8c7-4e80-90bb-be716fd0fb80)

- 각 endpoint routing 테스트

![image](https://github.com/user-attachments/assets/858a8721-2421-4c8f-b16e-5e1ca52669ad)

- 테스트용 스크립트

```yaml
#!/bin/bash

# HTTP_PORT는 Traefik의 web 엔트리포인트 NodePort
export HTTP_PORT=$(kubectl get svc -n traefik traefik -o jsonpath='{.spec.ports[?(@.name=="web")].nodePort}')

curl http://coffee.myweb.com:$HTTP_PORT

echo "----------------------------------------"

export HTTPS_PORT=$(kubectl get svc -n traefik traefik -o jsonpath='{.spec.ports[?(@.name=="websecure")].nodePort}')

curl -k https://tea.myweb.com:$HTTPS_PORT

echo "----------------------------------------"

curl -k https://www.myweb.com:$HTTPS_PORT/juice

echo "----------------------------------------"

curl -k https://www.myweb.com:$HTTPS_PORT/water
```

### Traefik Certificate

```bash


#!/bin/bash

echo "Adding Traefik certificate to the cluster..."
echo "Creating a self-signed certificate for Traefik..."

# -subj 옵션으로 인증서 정보 설정
sudo openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
  -keyout myweb01.key \
  -out myweb01.crt \
  -subj "/C=KR/ST=Seoul/L=Seoul/O=MyOrganization/OU=IT/CN=myweb01.example.com"

echo "인증서 생성 완료"

echo "인증서 권한 변경..."
sudo chmod 644 myweb01.key

echo "Creating a secret for Traefik..."
kubectl create secret tls myweb-tls \
  --cert=myweb01.crt \
  --key=myweb01.key \
  -n kube-system

echo "인증서 및 시크릿 생성 완료"

```

### 환경구축 및 테스트

- storageClass

```yaml
# Longhorn을 기본 스토리지 프로비저너로 사용하는 StorageClass 생성
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-storage-class
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: driver.longhorn.io
allowVolumeExpansion: true
parameters:
  numberOfReplicas: "3"
  staleReplicaTimeout: "30"
  fromBackup: ""
```

- PersistentVolumeClaim

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce # 단일 노드에서 읽기/쓰기 접근 권한
  volumeMode: Filesystem # FileSystem ,
  storageClassName: longhorn-storage-class
  resources:
    requests:
      storage: 1Gi
```

- PersistentVolume과 연결할 pod

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: date-pod
  namespace: default
  labels:
    app: date
spec:
  replicas: 1
  selector:
    matchLabels:
      app: date
  template:
    metadata:
      labels:
        app: date
    spec:
      containers:
        - name: date-pod
          image: busybox
          command:
            - "/bin/sh"
            - "-c"
            - "while true; do date >> /data/pod-out.txt; cd /data; sync; sync; sleep 30; done"
          volumeMounts:
            - name: date-vol
              mountPath: /data
      volumes:
        - name: date-vol
          persistentVolumeClaim:
            claimName: longhorn-pvc
```
