### DISCUSSION TITLE
Ch11. 스토리지 볼륨 스냅샷 사용하기

### DISCUSSION THREAD

**Discussion by YuDeokRin** [studykuberstep24/studykuberstep24#76] [덕린]
# ch11. 스토리지 볼륨 스냅샷 사용하기

- OpenEBS 호스트패스 스토리지는 성능은 뛰어나지만 단일 노드에 종속되고 스냅샵 등의 스토리지 부가 기능을 사용할 수 없다.
- 쿠버네티스는 CSI(Container Storage Interface)라는 추가 리소스를 이용해 벤더 독립적으로 스토리지 부가 기능을 사용할 수 있다.
- CSI는 쿠버네티스 코어 코드에서 분리되어 스토리지 솔루션 개발 업체는 코어 코드를 수정할 필요 없이 해
당 CSI 인터페이스를 준수하는 플러그인을 개발해서 자유롭게 필요한 기능을 추가할 수 있다.

### 오퍼레이터란

- 쿠버네티스에서 특정 애플리케이션의 패키징과 설치, 관리를 손쉽게 할 수 있도록 쿠버네티스API 확장 기능을 사용하는 컨트롤러이다.
- 오퍼레이터의 컨트롤러를 이용하면 애플리케이션이 항상 ‘의도한 상태’를 유지하기가 좀 더 용이하다.
- 오퍼레이터는 사용자 대신해서 애플리케이션과 복잡한 작업을 처리할 수 있어 다양한 솔루션 업체에서 설치나 관리 용도로 사용한다.

## ✅ 실습

- 루크 - 셰프 오퍼레이터 사용
- 셰프 스토리지를 설치하고 스냅샵 기능을 이용해 애플리케이션 데아터를 복구하는 실습 진행
- 쿠버네티스에서는 스냅샷도 하나의 리소스로서 YAML 파일을 이용해 편리하게 스냅샵을 생성할 수 있다.

### 🗒️실습과제

1. rook-ceph를 이용해 쿠버네티스 환경에서 사용 가능한 셰프 스토리지를 설치한다.
2. 워드프레스 애플리케이션을 설치하고 임의의 새로운 글을 게시한다. 해당 글을 포함하는 데이터를 백업하기 위해 스냅샷을 생성한다.
3. 생성한 스냅샷을 이용해 삭제한 블로그 글을 복구한다.

- 실습 과제 개요

![image](https://github.com/user-attachments/assets/5958c577-3b43-4a05-ab0f-2663740ce8f3)

## 1️⃣ rook-ceph를 이용한 쿠버네티스 셰프 스토리지 설치

- 셰프 스토리지의 각 노드별 디스크 구성

![image 1](https://github.com/user-attachments/assets/fbae8488-868a-4dce-a5a3-a4b979ee759c)

### 🗒️ 루크 오퍼레이터 설치

- git clone --single-branch --branch v1.9.2 [https://github](https://github/).com/rook/rook.git

<img width="862" alt="image 2" src="https://github.com/user-attachments/assets/c5cb585b-5eaa-4ce6-8a28-253db3d25e90" />

- 3개의 yaml 파일을 동시에 설치

<img width="868" alt="image 3" src="https://github.com/user-attachments/assets/7487bfb5-4502-422f-9cab-b91c6fb4e957" />

- rook-ceph 네임스페이스가 자동으로 생성된다.

<img width="876" alt="image 5" src="https://github.com/user-attachments/assets/b05b4568-b0e5-4dab-9b70-872ce468cc64" />

- 파드 조회 해보기

<img width="876" alt="image 5" src="https://github.com/user-attachments/assets/cd79cb17-248a-4337-b9a4-fc459294d478" />

🎉오퍼레이터 설치 완료 ! 🎉

### 🗒️ 셰프 클러스터 설치

- 루크는 CephCluster라는 별도의 CRD(CustomResourceDefinition)로 셰프 클러스터를 설치
- CephCluster 설정에서 개별 운영 요구사항에 맞게 디스크 , 노드 , 모니터링 등을 수정할 수 있습니다.
- 성능과 관련해서 서버와 디스크 사양에 따라 다양한 설정이 가능

- 기본 CephCluster 설정으로 설치 진행 후 조회

<img width="876" alt="image 6" src="https://github.com/user-attachments/assets/de06f435-1c78-4069-a3d2-dfceb7dee398" />

- 추가로 셰프 툴박스 파드를 설치 후 → 셰프 클러스트의 이상 유무를 확인

<img width="649" alt="image 7" src="https://github.com/user-attachments/assets/1415ddc2-f738-4a07-8fb2-0716f23132f7" />

- 이게 안됨 ….

<img width="1139" alt="image 8" src="https://github.com/user-attachments/assets/7558ab60-628a-4aee-8044-2188b25239ae" />

- 셰프 블록 스토리지 용 스토리지 클래스를 설치

<img width="1281" alt="image 9" src="https://github.com/user-attachments/assets/ab7d640a-0377-497c-99ac-7cbeb4625b1e" />

- kubernetes-csi 깃허브 저장소의 파일을 이용해 직접 설치

<img width="1380" alt="image 10" src="https://github.com/user-attachments/assets/3fc194fa-5c4c-4703-9539-eb05d3a96ef6" />

- 설치가 완료되면 volumesnapshot 관련 CRD 를 확인

<img width="942" alt="image 11" src="https://github.com/user-attachments/assets/854a210d-6d04-4764-9799-016f61897728" />

- napshot Controller를 설치

<img width="1371" alt="image 12" src="https://github.com/user-attachments/assets/353f1e81-60b7-4c71-9a04-dd6ed6f1b25d" />

- Rook 셰프 스냅샷 클래스 설치

<img width="804" alt="image 13" src="https://github.com/user-attachments/assets/7907969c-d582-4e59-aa94-baca5de29ab3" />

- 설치 완료 후 클래스 확인

<img width="885" alt="image 14" src="https://github.com/user-attachments/assets/74a9f72b-629a-4c50-a052-b19ac2ac8e58" />

## 2️⃣ 워드프레스 블로그 애플리케이션의 설치 및 스냅샷 생성

- 스냅샷을 이용한 워드프레스 데이터 복수

![image 15](https://github.com/user-attachments/assets/43197b43-8b0d-489d-8358-252855d86ae3)

### ✅ 워드프레스 애플리케이션 설치

- 워드프레스(Wordpress)는 블로그 용도로 많이 사용하는 애플리케이션이다.
- 루크에서는 쿠버네티스용 워드프레스 코드를 샘플 코드로 함께 제공해준다.

- 워드프레스 YAML 파일의 주요 구성 요소에 대한 설명

```yaml
apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  ports:
    - port: 80
  selector:
    app: wordpress
    tier: frontend
  type: LoadBalancer       # 워드프레스 웹서버를 로드밸러서 타입 서비스로 외부에 노출한다.
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pv-claim
  labels:
    app: wordpress
spec:
  storageClassName: rook-ceph-block  # 스토리지 클래스는 루크를 이용해 생성한 셰프 스토리지 클래스를 사용한다.
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
    tier: frontend
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
    spec:
      containers:
        - image: wordpress:4.6.1-apache # 워드프레스 웹서버는 아파치 웹서버를 사용한다.
          name: wordpress
          env:
            - name: WORDPRESS_DB_HOST
              value: wordpress-mysql #웹서버에서 데이터베이스 서버 연결은 쿠버네티스 클러스트 내부에서 이뤄지는 연결이므로 기존 가상 머신 환경처럼 IP 주소를 이용하지않는다.
            - name: WORDPRESS_DB_PASSWORD
              value: changeme
          ports:
            - containerPort: 80
              name: wordpress
          volumeMounts:
            - name: wordpress-persistent-storage
              mountPath: /var/www/html # 웹서버의 루트 디렉터리를 파드의 영구 볼륨으로 지정한다.
      volumes:
        - name: wordpress-persistent-storage
          persistentVolumeClaim:
            claimName: wp-pv-claim #웹서버 PVC YAML 파일의 PVC 이름을 동일하게 지정한다.
```

- rook-ceph PVC를 이용하는 워드프레스 MySQL 파드 YAML 파일 (mysql.yml)

```yaml
apiVersion: v1
kind: Service
metadata:
  name: wordpress-mysql # 웹서버에서 데이터베이스 서버 연결에 사용한 서비스 이름
  labels:
    app: wordpress
spec:
  ports:
    - port: 3306
  selector:
    app: wordpress
    tier: mysql
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim 
metadata:
  name: mysql-pv-claim
  labels:
    app: wordpress
spec:
  storageClassName: rook-ceph-block #PVC 생성용 스토리지 클래스를 셰프 스토리지 클래스로 지정한다.
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-mysql
  labels:
    app: wordpress
    tier: mysql
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: mysql
    spec:
      containers:
        - image: mysql:5.6 #MySQL 5.6 데이터베이스 서버를 사용 
          name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: changeme
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql #데이터베이스 서버의 데이터를 PVC에 저장
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim #PVC 이름을 지정한다. 해당 PVC는 데이터베이스 데이터로 사용한다.
```

### ✅ 워드프레스 설치

- 워드프레스용 새로운 네임스페이스 만들고 yaml 파일을 이용해 워드프레스 설치

<img width="652" alt="image 16" src="https://github.com/user-attachments/assets/ec5434d7-fed6-4dc8-9811-ed1b5adaf1cb" />

- wordpress, mysql 동시에 설치

<img width="697" alt="image 17" src="https://github.com/user-attachments/assets/49350660-531a-4264-906f-9a92f61fd22c" />

- 쉼표를 통해서 한번에 여러 개의 리소스를 조회할 수 있다.

<img width="1458" alt="image 18" src="https://github.com/user-attachments/assets/1d12bb1c-9e62-40a2-b78a-5bf93de59eb1" />
