### DISCUSSION TITLE
ch11. 스토리지 볼륨 스냅샷 사용하기

### DISCUSSION THREAD

**Discussion by vimkim** [studykuberstep24/studykuberstep24#78] [대현]
## 시작하기 앞서...

지난 주에 배웠던 OpenEBS 호스트패스의 단점은?

성능은 뛰어나지만 단일 노드에 종속되고 스냅샷 등의 부가 기능을 사용할 수 없다.

CSI 드디어 나온다.

Container Storage Interface라는 추가 리소스를 통해 벤더 독립적으로 스토리지 부가 기능을 사용할 수 있습니다.

쿠버네티스 코어 코드에서 분리되어, 스토리지 솔루션 개발 업체는 코어 코드를 수정할 필요 없이 CSI 인터페이스를 준수하는 플러그인을 개발해서 자유롭게 필요한 기능을 추가할 수 있습니다.

대표적인 오픈소스 스토리지 솔루션으로는 Ceph와 GlusterFS가 있습니다.

셰프는 block, file, object 3가지 타입의 서비스를 제공하고 확장성이 뛰어나 게임사 , 포털 등 국내의 대형 업체들이 많이 사용하고 있습니다.

---

## 오퍼레이터란?

쿠버네티스에서 특정 애플리케이션의 패키징과 설치, 관리를 손쉽게 할 수 있도록 쿠버네티스 API 확장 기능을 사용하는 컨트롤러입니다.

오퍼레이터 컨트롤러를 이용하면 의도한 상태를 유지하기가 좀 더 용이합니다.

오퍼레이터는 사용자를 대신해 애플리케이션과 관련된 복잡한 작업을 처리할 수 있어 다양한 솔루션 업체에서 설치나 관리 용도로 사용합니다.

섀프도 rook에서 제공하는 operator를 통해 설치할 수 있습니다.

Cassandra, NFS 등의 오퍼레이터도 제공합니다.

---

루크 셰프 오퍼레이터를 이용해 셰프 스토리지를 설치하고 스냅샷 기능을 이용해 애플리케이션 데이터를 복구하는 실습을 진행합니다.

쿠버네티스에서는 스냅샷도 하나의 리소스로서 YAML 파일을 이용해 편리하게 스냅샷을 생성할 수 있습니다.

---

## 01 rook-ceph를 이용한 쿠버네티스 셰프 스토리지 설치

```bash
k apply -f crds.yaml -f common.yaml -f operator.yaml

k ns rook-ceph

k get pod
```

---

루크는 CephCluster라는 별도의 CRD로 셰프 클러스터를 설치합니다.

```
k apply -f cluster.yaml
```

```
k get pod
```

```
k apply -f toolbox.yaml
```

```
k exec -n rook-ceph -it deployments/rook-ceph-tools -- bash
ceph status
```

셰프 블록 스토리지 용 스토리지 클래스 설치하기
```bash
k apply -f csi/rbd/storageclass.yaml 
```

스냅샷을 사용하기 위해 external-snapshotter와 스냅샷 클래스 설치하기

```
k apply -f ..../volumesnapshot-classes.yaml

k apply -f ..../volumesnapshot-contents.yaml

k apply -f ..../volumesnapshots.yaml
```

```
k get crd | grep volumesnap
```

```
k apply -f .../rbac-snapshot-controller.yaml

k apply -f .../setup-snapshot-controller.yaml
```

```
k apply -f csi/rbd/snapshotclass.yaml
```

```
k get volumesnapshotclasses.snapshot.storage.k8s.io
```

---

## 02 워드프레스 애플리케이션 설치

```
kind: Service

type: LoadBalancer

---

kind: PersistentVolumeClaim

storageClassName: rook-ceph-block

---

kind: deployment
containers:
    - image: wordpress

...
    volumeMounts:
      - name: wordpress-persistent-storage
        mountPath: /var/www/html

  volumes:
    - name: wordpress-persistent-storage
      persistentVolumeClaim:
        claimName: wp-pv-claim


```

- /var/www/html: 웹서버의 루트 리렉터리를 파드의 PV로 지정

---

워드프레스에서 사용하는 MySQL 파드의 YAML

```yaml

name: wordpress-mysql

---

kind: PersistentVolumeClaim
...
storageClassName: rook-ceph-block

---

kind: Deployment
    containers:
       - image: mysql:...
    volumeMounts:
      - name: mysql-persistent-storage
        mountPath: /var/lib/mysql
    volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
```

```
k create ns wordpress
k ns wordpress

k apply -f wordpress.yaml -f mysql.yaml
```

```
k get pod,svc,pvc
```

### 11.2.2 스토리지 볼륨 스냅샷 생성

```
k get pvc, volumesnapshotclasses.snapshot.storage.k8s.io
```

MySQL 데이터를 백업하는 스냅샷 YAML 파일
```yml
kind: VolumeSnapshot
...
spec:
  volumeSnapshotClassName: csi-rbdplugin-snapclass
  source:
    persistentVolumeClaimName: mysql-pv-claim
```

```
k apply -f mysql-pvc-snapshot.yml
```

스냅샷 확인

```
k get volumesnapshot
```

스냅샷 컨텐츠 확인

```
k get volumesnapshotcontents.snapshot.storage.k8s.io
```

---
## 03 스냅샷을 이용한 애플리케이션 데이터 복구

```
k scale deployment wordpress-mysql --replicas 0

k delete pvc mysql-pv-claim
```

PVC를 삭제하기 위해 파드도 삭제

복구하는 yaml

```yml
kind: PersistentVolumeClaim

name: mysql-pv-claim

storageClassName: rook-ceph-block
dataSource:
  name: mysql-snapshot-01
```

```
k apply -f snap-restore-pvc.yml
k get pvc
```

복구 성공했으니 mysql 파드를 다시 생성

```
k scale deployment wordpress-mysql --replicas 1
k get pod
```

---

## 04 rock-ceph 스토리지의 가용성 테스트 및 IOPS 성능 측정

분산 파일 시스템을 사용하는 셰프 스토리지의 장점과 단점

- 특정 노드가 다운되어도 다른 노드에서 데이터를 분산 처리할 수 있어 고가용성을 보장할 수 있음.
- 여러 노드에서 서비스해서 각 노드 간 분산 파일 처리에 필요한 오버헤드가 발생해서 단일 호스트패스를 이용하는 것에 비해 성능이 저하

```
k get pod -o wide
k drain ubun20-03 --delete-emptyudir-data --ignore-daemonsets
```
03번 호스트가 종료

```
k get pod -o wide -w
k get pod
```

MySQL 파드가 ubuntu20-02로 이동해서 정상 실행

PVC를 사용해도 특정 노드에 종속되지 않아 다른 노드로 이전해서 파드가 실행됩니다.

분산 파일 시스템을 사용하는 스토리지의 장점입니다.

```
k uncordon ubun20-03
```

---

스토리지 IOPS 성능 측정

```
kubestr fio -s rook-ceph-block -f ..../fio-read.fio
```

평균 읽기 IOPS = 2353

이전 OpenEBS 호스트패스 환경의 IOPS 12609에 비해 약 5배 정도 감소한다.

---

### 정리

```
k delete deployments.apps --all
k delete pvc --all
```

- CSI를 이용하여 스냅샷 등 부가 기능을 이용할 수 있다.
- 셰프 스토리지는 단일 솔루션에서 분산 파일 구조의 블록, 파일, 오브젝트 타입과 스냅샷 등 부가 스토리지 기능을 지원하는 오픈소스 솔루션입니다.
	- 스토리지 확장성 등이 뛰어나고 많은 레퍼런스 보유
- 루크는 다양한 스토리지 솔루션 설치할 수 있는 오퍼레이터 제공
- 워드프레스 + MySQL 백업 및 복구
- 스냅샷 클래스, 볼륨 스냅샷 콘텐츠, 볼륨 스냅샷 드으이 추가 리소스를 필요로 한다.
- 스냅샷을 이용하면 일부 데이터 또는 PVC가 삭제되어도 기존에 생성한 스냅샷으로 해당 시점의 데이터를 PVC로 복구할 수 있습니다.
- 로컬 호스트패스에 비해 약 5배 정도 IOPS 성능이 떨어진다.
