### DISCUSSION TITLE
ch13. 하버를 이용한 로컬 컨테이너 이미지 저장소 구축

### DISCUSSION THREAD

**Discussion by yeongki0944** [studykuberstep24/studykuberstep24#82] [영기]
# 13. 하버를 이용한 로컬 컨테이너 이미지 저장소 구축

<img width="1440" alt="image" src="https://github.com/user-attachments/assets/e80464a0-31ad-4f04-9a2d-232186c569a6" />
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/94eccd44-7ac5-4490-bdb6-f59cc167791c" />
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/820a1172-0ce0-4343-b1ac-77eb489b4e87" />
<img width="1380" alt="image" src="https://github.com/user-attachments/assets/e2d0e22a-849d-4aa6-9efd-0a3a1ac0c77c" />
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/38be9d0d-c3c7-4853-837d-ec6440209b0f" />

## 실습과제

- 헬름 차트를 이용해 하버 컨테이너 이미지 저장소를 설치
- 로컬 PC에서 생성한 컨테이너 이미지를 하버 저장소로 업로드
- Deployment YAML 파일의 컨테이너 이미지 저장 소를 사설 하버 저장소로 변경
- 하버 리포지토리 이미지 취약점 자동 스캔 기능 활성화
- NGINX, busybox 이미지의 보안 취약점 확인

# 쿠버네티스 Harbor 컨테이너 이미지 저장소 구축 가이드

이 문서는 Kubernetes 1.28 버전에서 Harbor 컨테이너 이미지 저장소를 구축하는 방법을 안내합니다.

## 환경 정보
- Kubernetes 버전: 1.28
- OS: Ubuntu 22.04
- 구성: 마스터 노드 1대, 워커 노드 2대
- EC2 인스턴스: AWS EC2 t3.large (마스터 및 워커 노드)

## 0. NGINX Ingress Controller 설치

Helm을 사용하여 NGINX Ingress Controller를 설치

```bash
# Ingress NGINX 레포지토리 추가
helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
helm repo update
```

```bash
# NodePort 타입으로 NGINX Ingress Controller 설치
helm install ingress-nginx ingress-nginx/ingress-nginx \
  --namespace ingress-nginx \
  --create-namespace \
  --set controller.service.type=NodePort \
  --set controller.service.nodePorts.http=30080 \
  --set controller.service.nodePorts.https=30443
```

설치 상태 확인

```bash
kubectl get pods -n ingress-nginx
kubectl get svc -n ingress-nginx
```

테스트용 Nginx 웹 서버를 배포하고 Ingress로 노출
```bash
# 테스트용 네임스페이스 생성
kubectl create namespace test-app
```

 Nginx 배포

```yaml
cat <<EOF | kubectl apply -f - -n test-app
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-test
  labels:
    app: nginx-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-test
  template:
    metadata:
      labels:
        app: nginx-test
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-test
spec:
  selector:
    app: nginx-test
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
EOF
3. Ingress 리소스 생성
테스트 애플리케이션을 위한 Ingress 리소스를 생성합니다:
bashcat <<EOF | kubectl apply -f - -n test-app
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-test-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: nginx-test.myweb.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-test
            port:
              number: 80
EOF
```

4. 테스트 설정 및 확인

```bash
# 호스트 파일 설정
# 마스터 노드 IP를 사용 (여기서는 예시로 마스터 노드의 IP를 확인하는 명령어를 사용)
MASTER_IP=$(kubectl get nodes -o jsonpath='{.items[0].status.addresses[?(@.type=="InternalIP")].address}')
echo "$MASTER_IP nginx-test.myweb.io" | sudo tee -a /etc/hosts
```

## 1. Helm 설치

마스터 노드에서 Helm을 설치합니다:

```bash
# Helm 설치 스크립트 다운로드 및 실행
curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

# 설치 확인
helm version
```

## 2. Harbor Helm 차트 준비

```bash
# Harbor Helm 리포지토리 추가 및 업데이트
helm repo add harbor https://helm.goharbor.io
helm repo update

# 최신 Harbor 버전 확인
helm search repo harbor/harbor

# Harbor Helm 차트 다운로드
helm pull harbor/harbor

# 압축 해제 및 설정 파일 준비
tar -zxvf harbor-*.tgz
cd harbor
cp values.yaml my-values.yaml
```

## 3. Harbor 설정 파일 수정

설정 파일에서 주석을 제거하고 내용을 확인하는 명령어:

```bash
# 주석을 제거하고 설정 파일 내용 확인
grep -v "^\s*#" my-values.yaml
```

`my-values.yaml` 파일을 수정합니다:

```bash
vi my-values.yaml
```

주요 수정 사항:

```yaml
expose:
  type: nodePort  # ingress 대신 nodePort로 변경
  tls:
    enabled: false  # TLS 사용하지 않음 (간단한 데모용)
  nodePort:
    name: harbor
    ports:
      http:
        port: 80
        nodePort: 30002  # HTTP 포트
      https:
        port: 443
        nodePort: 30003  # HTTPS 포트

# 마스터 노드 IP 사용 (여기서는 54.153.70.63 사용)
externalURL: http://54.153.70.63:30002

# 관리자 비밀번호 설정
harborAdminPassword: "Harbor12345"

# Persistence 설정
persistence:
  enabled: true
  persistentVolumeClaim:
    registry:
      size: 5Gi
    database:
      size: 1Gi
    redis:
      size: 1Gi
    trivy:
      size: 2Gi
```

## 4. Harbor 설치

```bash
# Harbor 네임스페이스 생성
kubectl create namespace harbor

# Harbor 설치
helm install harbor -f my-values.yaml . -n harbor

# 설치 상태 확인
kubectl get pods -n harbor -w
```

모든 Pod가 Running 상태가 될 때까지 기다립니다.

## 5. Harbor 설정 업데이트 (필요시)

이미 Harbor를 설치한 후 설정을 변경해야 할 경우:

```bash
# 설정 파일 수정 (예: type을 ingress에서 nodePort로 변경)
vi my-values.yaml

# Helm으로 Harbor 업데이트
helm upgrade harbor -f my-values.yaml . -n harbor

# 업데이트 상태 확인
kubectl get pods -n harbor
kubectl get svc -n harbor
```

## 6. Harbor 외부 접속 테스트

브라우저에서 다음 URL로 접속:
```
http://54.153.70.63:30002
```

기본 로그인 정보:
- 사용자: admin
- 비밀번호: Harbor12345 (my-values.yaml에서 설정한 값)

## 7. 로컬 Docker 설정 및 이미지 푸시

로컬 PC에서 Harbor에 이미지를 푸시:

```bash
# Docker 로그인
docker login 54.153.70.63:30002 -u admin -p Harbor12345

# 테스트 이미지 준비
docker pull busybox
docker tag busybox 54.153.70.63:30002/library/busybox:1.0

# Harbor로 이미지 푸시
docker push 54.153.70.63:30002/library/busybox:1.0
```

## 8. 각 쿠버네티스 노드 containerd 설정

모든 노드(마스터, 워커1, 워커2)에서 다음 설정을 추가:

```bash
# containerd 설정 파일 백업
sudo cp /etc/containerd/config.toml /etc/containerd/config.toml.bak

# 설정 파일 수정
sudo vi /etc/containerd/config.toml
```

설정 파일에 다음 내용 추가:
```toml
[plugins."io.containerd.grpc.v1.cri".registry]
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors]
    [plugins."io.containerd.grpc.v1.cri".registry.mirrors."54.153.70.63:30002"]
      endpoint = ["http://54.153.70.63:30002"]
  [plugins."io.containerd.grpc.v1.cri".registry.configs]
    [plugins."io.containerd.grpc.v1.cri".registry.configs."54.153.70.63:30002".tls]
      insecure_skip_verify = true
```

containerd 재시작:
```bash
sudo systemctl restart containerd
```

## 9. 쿠버네티스에서 Harbor 이미지 사용

```bash
# Harbor 이미지를 사용하는 테스트 Pod 생성
cat <<EOF | kubectl apply -f -
apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-test
  labels:
    app: busybox-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox-test
  template:
    metadata:
      labels:
        app: busybox-test
    spec:
      containers:
      - name: busybox
        image: 54.153.70.63:30002/library/busybox:1.0
        command:
        - "/bin/sh"
        - "-c"
        - "sleep 3600"
EOF
```

필요시 자격 증명 시크릿 생성:
```bash
kubectl create secret docker-registry harbor-cred \
  --docker-server=54.153.70.63:30002 \
  --docker-username=admin \
  --docker-password=Harbor12345

kubectl patch deployment busybox-test -p '{"spec":{"template":{"spec":{"imagePullSecrets":[{"name":"harbor-cred"}]}}}}'
```

## 10. Harbor 이미지 자동 스캔 설정

1. Harbor UI 접속: http://54.153.70.63:30002
2. 관리자 로그인: admin / Harbor12345
3. 프로젝트 > library > 구성
4. "푸시할 때 자동으로 이미지 스캔" 옵션 활성화

## 11. 우분투 22.04에 Docker 설치 및 Harbor 이미지 푸시 테스트

Harbor에 이미지를 푸시하기 위해 마스터 노드에 Docker를 설치합니다:

```bash
# 필요한 패키지 설치
sudo apt-get update
sudo apt-get install -y ca-certificates curl gnupg

# Docker 공식 GPG 키 추가
sudo install -m 0755 -d /etc/apt/keyrings
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
sudo chmod a+r /etc/apt/keyrings/docker.gpg

# Docker 저장소 추가
echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

# Docker 설치
sudo apt-get update
sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

# Docker 서비스 시작 및 자동 시작 설정
sudo systemctl start docker
sudo systemctl enable docker
```

### 안전하지 않은 레지스트리 설정

HTTP 프로토콜로 Harbor에 접근하기 위해 Docker에 안전하지 않은 레지스트리를 설정합니다:

```bash
# Docker 데몬 설정 파일 생성
sudo mkdir -p /etc/docker
cat > /etc/docker/daemon.json <<EOF
{
  "insecure-registries": ["54.153.70.63:30002"]
}
EOF

# Docker 재시작
sudo systemctl restart docker
```

### 이미지 푸시 테스트

```bash
# Harbor 로그인
docker login 54.153.70.63:30002 -u admin -p Harbor12345

# 성공 메시지 확인
# WARNING! Using --password via the CLI is insecure. Use --password-stdin.
# WARNING! Your credentials are stored unencrypted in '/root/.docker/config.json'.
# Configure a credential helper to remove this warning. See
# https://docs.docker.com/go/credential-store/
# Login Succeeded
```

## 12. PVC Pending 문제 해결 - 영구 저장소 비활성화

Harbor 설치 시 PVC가 Pending 상태로 남아있는 경우 (스토리지 클래스가 없는 환경):

```bash
# PVC 상태 확인
kubectl get pvc -n harbor
# NAME                              STATUS    VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS   AGE
# data-harbor-redis-0               Pending                                                     11m
# data-harbor-trivy-0               Pending                                                     11m
# database-data-harbor-database-0   Pending                                                     11m
# harbor-jobservice                 Pending                                                     11m
# harbor-registry                   Pending                                                     11m
```

### 영구 저장소 비활성화하여 Harbor 재설치

테스트 환경에서는 영구 저장소를 비활성화하여 설치할 수 있습니다:

```bash
# 기존 Harbor 제거
helm uninstall harbor -n harbor
kubectl delete pvc --all -n harbor

# my-values.yaml 파일에서 persistence 설정 변경
vi my-values.yaml
# persistence:
#   enabled: false 로 변경

# Harbor 재설치
helm install harbor harbor/harbor -f my-values.yaml -n harbor

# 또는 간단한 설정 파일로 설치
cat > harbor-simple.yaml <<EOF
expose:
  type: nodePort
  tls:
    enabled: false
  nodePort:
    ports:
      http:
        port: 80
        nodePort: 30002
      https:
        port: 443
        nodePort: 30003
externalURL: http://54.153.70.63:30002
harborAdminPassword: "Harbor12345"
persistence:
  enabled: false
EOF

helm install harbor harbor/harbor -f harbor-simple.yaml -n harbor
```

## 13. NGINX, busybox 이미지 취약점 스캔 테스트

```bash
# NGINX 이미지 Pull 및 Tag
docker pull nginx:latest
docker tag nginx:latest 54.153.70.63:30002/library/nginx:latest

# Harbor로 이미지 푸시
docker push 54.153.70.63:30002/library/nginx:latest

# busybox 이미지도 동일하게 진행
docker pull busybox
docker tag busybox 54.153.70.63:30002/library/busybox:latest
docker push 54.153.70.63:30002/library/busybox:latest

# Harbor UI에서 취약점 확인
# 프로젝트 > library > 리포지토리 > nginx/busybox > 취약점 탭
```

---

이 가이드는 Kubernetes 클러스터에 Harbor 컨테이너 이미지 저장소를 설치하고 기본적인 사용법을 안내합니다. 또한 설치 중 발생할 수 있는 문제와 그 해결 방법을 포함합니다. 프로덕션 환경에서는 영구 저장소와 보안 설정을 적절히 구성하는 것이 좋습니다.

# Ref

https://www.cyberithub.com/how-to-install-harbor-on-ubuntu-20-04-lts-step-by-step/
https://www.digitalocean.com/community/tutorials/how-to-secure-apache-with-let-s-encrypt-on-ubuntu

- Certificate key 저장 위치
  - Certificate is saved at: /etc/letsencrypt/live/jenkins-test.link/fullchain.pem
  - Key is saved at:         /etc/letsencrypt/live/jenkins-test.link/privkey.pem
