### DISCUSSION TITLE
ch14. 깃랩을 이용한 로컬 Git 소스 저장소 구축

### DISCUSSION THREAD

**Discussion by yeongki0944** [studykuberstep24/studykuberstep24#86] [영기]
# 쿠버네티스 환경에 GitLab 설치 가이드

## 01. 클러스터 환경

- **쿠버네티스 버전**: 1.28 (Ubuntu 22.04)
- **클러스터 구성**:
  - k8s-master (t3.large, 54.153.70.63)
  - k8s-worker1 (t3.large, 54.153.84.43)
  - k8s-worker2 (t3.large, 3.101.142.27)
- **Ingress Controller**: NodePort 타입 NGINX Ingress Controller (포트 30080, 30443)
- **스토리지**: PV/PVC 설정 없음

### 헬름 저장소 추가 및 차트 다운로드

```bash
# 깃랩 헬름 저장소 추가
helm repo add gitlab https://charts.gitlab.io/
helm repo update

# 깃랩 헬름 차트 다운로드
helm pull gitlab/gitlab --version 6.11.0 --untar
cd gitlab
```

### my-values.yaml 설정

기본 values.yaml 파일을 복사하여 수정합니다:

```bash
cp values.yaml my-values.yaml
```

아래는 PV/PVC가 없는 환경과 NodePort 타입에 맞게 수정한 my-values.yaml 파일의 주요 설정입니다:

```yaml
global:
  hosts:
    domain: myweb.io
    https: false
  ingress:
    configureCertmanager: false
    provider: nginx
  
  # 모든 오브젝트 스토리지 비활성화
  appConfig:
    lfs:
      enabled: false
    artifacts:
      enabled: false
    uploads:
      enabled: false
    packages:
      enabled: false
    externalDiffs:
      enabled: false
    terraformState:
      enabled: false
    ciSecureFiles:
      enabled: false
    dependencyProxy:
      enabled: false
    backups:
      bucket: gitlab-backups

# 불필요한 서비스 비활성화
certmanager:
  install: false
prometheus:
  install: false
gitlab-runner:
  install: false

# 기본 제공 인그레스 컨트롤러 비활성화
nginx-ingress:
  enabled: false

# Redis 활성화
redis:
  install: true

# PostgreSQL 설정
postgresql:
  install: true
  persistence:
    enabled: false

# GitLab 서비스 설정
gitlab:
  webservice:
    service:
      type: NodePort
      nodePort:
        http: 30080
        https: 30443
  gitlab-shell:
    service:
      type: NodePort
      nodePort: 30022
  gitaly:
    persistence:
      enabled: false
  minio:
    enabled: true
    persistence:
      enabled: false
  toolbox:
    backups:
      objectStorage:
        backend: "s3"
        config:
          key: config
```

### 네임스페이스 생성 및 설치

```bash
# 네임스페이스 생성
kubectl create namespace gitlab

# 깃랩 설치
helm install gitlab -f my-values.yaml . --namespace gitlab
```

### 설치 과정에서 발생한 문제 및 해결

1. **PV/PVC 관련 문제**: Gitaly, PostgreSQL, Redis, Minio 등의 Pod가 Pending 상태로 대기
   - 해결방법: 각 컴포넌트의 persistence.enabled 값을 false로 설정

2. **오브젝트 스토리지 관련 문제**: LFS, artifacts, uploads, packages 등의 스토리지 설정 필요
   - 해결방법: global.appConfig 아래 각 스토리지 기능을 비활성화

3. **Redis 설정 문제**: Redis 비활성화 시 외부 Redis 설정 필요
   - 해결방법: redis.install을 true로 유지

### 설치 확인

```bash
# Pod 상태 확인
kubectl get pods -n gitlab

# 서비스 확인
kubectl get svc -n gitlab
```

### 초기 비밀번호 확인

```bash
# 초기 root 비밀번호 확인
kubectl get secret -n gitlab gitlab-gitlab-initial-root-password -ojsonpath='{.data.password}' | base64 --decode ; echo
```

## 04. GitLab 접속

브라우저에서 다음 URL로 접속:
```
http://<마스터노드IP>:30080
```

- 사용자 이름: root
- 비밀번호: 위에서 확인한 초기 비밀번호

## 주의 사항

1. 이 설정은 영구 저장소 없이 테스트 목적으로만 사용해야 합니다.
2. 실제 운영 환경에서는 적절한 PV/PVC 설정이 필요합니다.
3. 모든 Pod가 Running 상태가 될 때까지 기다려야 할 수 있습니다(약 5-10분 소요).
