### DISCUSSION TITLE
Ch 15. ArgoCd를 활용한 CICD

### DISCUSSION THREAD

**Discussion by yjinheon** [studykuberstep24/studykuberstep24#91] [진헌]
## 사전준비 

- helm chart로 설치한 gitlab 환경
- kubernetes (minikube)

### helm chart 이용한 Argocd 설치

**설치 스크립트 활용**

```bash

#!/bin/bash

echo "add helm repo argocd"

helm repo add argo https://argoproj.github.io/argo-helm

echo "update helm repo"

# set helm path

HELM_REPO=~/helm-repo

helm pull argo/argo-cd --destination $HELM_REPO

echo "argocd Helm Chard downloaded to $HELM_REPO"

tar xvfz $HELM_REPO/argo-cd-*.tgz -C $HELM_REPO

echo "argocd Helm Chart extracted to $HELM_REPO"

```

**my.values 수정**

![image](https://github.com/user-attachments/assets/3497cabc-551d-4b17-bcda-2604e2113c9b)

**argo-cd namespace 생성 후 설치**

```bash
helm install argocd -f my-values.yaml .
```

![image](https://github.com/user-attachments/assets/d6ea755c-64e4-4cdc-9714-7d5d43a9bf7c)

### argo cd 접근

**minikube tunnel**

로컬 kubenetis를 사용할 경우 기본적으로 external ip가 할당이 안되기 때문에 터널링을 통해 external ip 할당

- 로컬 컴퓨터의 네트워크 스택을 조작하여 새로운 라우팅 규칙을 생성
- LoadBalancer 서비스에 로컬 IP 주소를 할당
- 해당 IP로 들어오는 트래픽을 minikube 클러스터 내 서비스로 라우팅

````bash
minikube tunnel
````

**argocd password확인**

```bash
 kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d
```

### argocd 접속

**argocd 초기화면**

![image](https://github.com/user-attachments/assets/cb90a37a-9015-4562-9e2b-ca52b31de4b6)

### argocd CLI

**cli 설치**

```bash
yay -S argocd
```

**로그인**

```bash
argocd login 10.99.177.179 --username admin
```

**git repository 등록**

- 테스트용으로 생성한 repository 등록

```bash
argocd repo add https://gitlab.192.168.59.101.nip.io/mygroup/spring-basic.git --username jinheon --insecure-skip-server-verification

```

**repo list 확인**

![image](https://github.com/user-attachments/assets/b439b32d-87d5-4eb1-a515-cfc4b829b3cc)

### helm chart git repository 동기화

![image](https://github.com/user-attachments/assets/5e8b5718-29e4-4fa5-8a73-f6bb2ee869e1)

### argocd application yaml

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq-helm
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: rabbitmq
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://gitlab.192.168.59.101.nip.io/mygroup/spring-basic.git
    path: rabbitmq
    targetRevision: HEAD
    helm:
      valueFiles:
      - my-values.yaml
  syncPolicy:
    syncOptions:
    - CreateNamespace=true 
```

### Sync 오류

![image](https://github.com/user-attachments/assets/2562ccc6-534a-4785-9422-cad763fc49fd)

### UI 로 동기화

- cli도 동기화 하는 방법도 있을듯

![image](https://github.com/user-attachments/assets/650c6a36-5773-464d-96c7-3cd47bfe67d8)

## 3. 리소스 편집 

- 실행중 인 deployment의 상태를  k edit 명령어로 편집하여 이미지 버전을 변경할 수 있다.
